### ISSUE TITLE
Progress ..fetching result page 2/200

### ISSUE THREAD

**Issue by tsinggu** [ljay79/jira-tools#100]
I am getting a popup Progress.. fetching result page 2/200 while trying to fetch data using my own filter but not getting any results at all. The add on is giving me the list of all my filters so there is no connection issue. 

Can you please help?

**Comment by ljay79** [comment]
Hi @tsinggu 

if you dont mind, pelase activate Debugging in "About" dialog, provide me your "Temp. User Key" and then perform at least one another try. This way it will log possible errors and information to my StackDriver logging account where i can analyze it better.
User credentials are not transmitted in any log data.

**Comment by tsinggu** [comment]
@ljay79 Here is the temp user key "AJP21zXXb2+MT32rnEoqchb1TgaLnHACNL4mDt/Q3f0JqML+VEHq7VbSieQLEcyNoDi8FjctRCTb". I have run the report again.
Thanks

**Comment by tsinggu** [comment]
@ljay79 I got the results this time but it seems its not the results from the filter that I have chosen. It seems that it takes a lot of time to respond back because its trying to get data across all projects in JIRA. I tried with multiple filters and I am getting the same set of results which is incorrect.

Thanks

**Comment by ljay79** [comment]
Hmmm. sounds strange.
Regarding the "slow", are you using Jira on a self hosted server or the Cloud Service?
So far, multiple users having no issues with speed even with more result sets then yours.

About the results itself. If you getting results, that would be the data your Jira is returning for the Filter.
The sorting will differ even if you define a ORDER BY in your filter, the Jira API might not return it in that specified order.
I wont be able on checking the actual results are correct as i can not compare it to anything.

My suggestion; try to find the issue by going slowly from small to bigger and more complex filters.
Use a test filter with simple logic and only few expected results.
Then compare and if correct, increase filter complexity.

For the beginning, you should also try to keep the resulting Fields/Columns as low as possible which would speed up the processing a lot.

Sry for not being able to assist much more at this point. Let me know about your progress and where else i might be helpful.

**Comment by ljay79** [comment]
BTW: I see a lot - i mean a lot - of logs from unsupported fields.
Try to use less custom fields.
The lookup of a format for all custom field is time and ressource consuming slowing down entire process.

Currently not supported fields i found from your logs:
versions
issuelinks
aggregatetimeoriginalestimate
lastViewed
subtasks
votes
watches
environment
workratio

**Comment by tsinggu** [comment]
@ljay79 I am running these reports using only one custom field and have selected only 3-4 standard fields. The actual filter using JIRA only returns 40-45 records. The results are the same on every filter that I am have tried using the plug in and you are right, its returning a bunch of unsupported fields. Its actually picking up tickets from different projects as well. Its not at all matching with the filter results.

**Comment by ljay79** [comment]
Yesterday 10/31 between 16:25 and 17:58 UTC+0 i can see multiple dozends of thousands of log entires when it tries to format a response field (custom field) which isnt supported.
Looks like you used filter:
_id: 97551_
_name: LSTDEV Force_
The add-on basically will fetch the used JQL from the filter and then perform a search against your Jira with that JQL query.
For above Filter, the JQL appears to be:
`project in ("Learning Services Technology Development Escalations") AND type in (bug, rework, task) AND component in (Force)`

The Jira API will return same results on the API as when you do it inside Jira website.
Unless, you use a different user - as different user permission might result in different search results.

Tip: Use a new custom filter for testing. Keep it simple like the one above with only 40-45 records.
Save it under a unique name. Then try it in the Add-On.
BTW: In case you update the filter in Jira, it might take some seconds/minutes before its updated and available for the API. Jira, Google and the Add-On using a mix of caches.
Using a new filter with unique name, will make sure, you see the correct filter and JQL inside the Add-On.

Let me know, with an updated "temp user key" and time frame, when i can lookup more logs for you.

**Comment by ljay79** [comment]
Hi @tsinggu , I'd like to follow up with you on that issue.
Just checking if i can close that issue or if you do have further insights or troubles which i can assist on for this specific issue.

(For any other issues, please open a new issue report)

**Comment by ljay79** [comment]
[abandoned]
