### ISSUE TITLE
Columns are swapped when refreshing sheet (option List issues from filter)

### ISSUE THREAD

**Issue by mvervark** [ljay79/jira-tools#102]
Awesome add-on! Very happy with it!
I discovered a small bug though:

When I refresh the sheet with option 'List issues from filter', the columns B & C are swapped randomly.
Since I made some references in Sheets (VLOOKUP based on these columns),  the VLOOKUP gives sometimes the wrong information after refresh.
I would be very happy if this was solved.
Another question: How is the order of the columns determined? They are not matching the columns which I defined in the Jira-filter...

**Comment by ljay79** [comment]
Hi @mvervark 

I certainly can have a look on that.

In general, the columns/order of columns can not be defined in the JQL (filters).
The resulting order is based on whatever the JIRA api does return to the script. That might be the reason why its not always the same order - even it wouldnt make sense, that JIRA or anything would randomly re-sort the order.

Are these some specific columns/fields which get swapped? JIRA Fieldnames?

If you can, please provide me with the JQL query here, maybe i am able to replicate the behavior on my Jira instance.

**Comment by ljay79** [comment]
hmmm...  i tried to replicate and wasnt able to reproduce it.
Also reviewing the code and api data, nothing indicates atm that it possibly can be toggled randomly.

For further research i would like to ask you to enable the debugging in the About dialog, then reproduce the issue.
The temp user key i would need from you (About dialog) so i can look up the debugging logs here...

**Comment by ljay79** [comment]
I do expirience the issue as well now. Didnt noticed before. Will see what i can do to fix this.

**Comment by ljay79** [comment]
@mvervark a new version 1.0.4 has just been rolled out today whch should fix this issue.
Please check if you can confirm. Thx

**Comment by ljay79** [comment]
Ahh Ahh damn,  while reading I think I know why. Will fix asap

**Comment by ljay79** [comment]
BugFix is submitted, i'll give you another note once Google has approved and is rolling out the update.
Was my bad = poor testing

**Comment by mvervark** [comment]
Hi Jens,

It works perfectly again!
Thanks a lot!!!

**Comment by mvervark** [comment]
Hi Jens,

It works perfectly now!
Thanks a lot!

**Comment by ljay79** [comment]
I would appriciate honest rating and/or review within Google Marketplace on my Add-on. 🥇 👍
