### ISSUE TITLE
Time Spent in hours for issues filter

### ISSUE THREAD

**Issue by sleepercode** [ljay79/jira-tools#103]
Hot to fetch Time Spent in hours for the issue filter sheet, currently it is only fetching in seconds.
![sheet](https://user-images.githubusercontent.com/6087214/48914062-a9621b80-ee7a-11e8-8389-24802190f386.PNG)

**Comment by ljay79** [comment]
At the moment you could only format the values into your desired format in another cell.
https://productforums.google.com/forum/#!topic/docs/2ok8gbIAe0M

Sample: add new column and enter a formula like "=<TimeSpent Cell coord here>/(24*60*60)" then use format of duration HH:mm:ss or similar. See above link where this is better explained.﻿

**Comment by sleepercode** [comment]
I know that i can format cell, but whats is the point of this addon. Time spent should be in hh and format 0.00.

I know where to edit the plugin it is in JiraCommon.gs line 470

**case 'timespent':**  // currently timespent shows in seconds

//Update to get time in hours
      case 'timespent':
      resp = {
            value : parseFloat(data.fields[attrib] / 3600) || null,
            format: "0.00"
          };
          break;

**Comment by ljay79** [comment]
Hi @sleepercode a new version has been rolled out today.
You should notice a new format of any time duration columns, hope this finds your like.
In settings you can still switch back to old format in seconds.
