### ISSUE TITLE
Custom fields not showing

### ISSUE THREAD

**Issue by peter-cnp** [ljay79/jira-tools#105]
Hi,

The custom fields are not downloading any more but all other system fields are downloading fine. I've been using Jira Sheet Tools v1.0.4 with the same settings and the same jira list filter sets for a couple of weeks and this issue just started this morning.

Please help!

P.S. - I'd like to extend my deepest thanks to the developers who made this fantastic add-in!

**Comment by Paul0975** [comment]
Hi ,
I too face the same issue and using version V.1.0.4.
Temp. User Key:

AEt9bgR6NdlbomtuXtSjObhnJDNDeuqZKms1TctuNPZXGbCSVIw+7PP/R+ni8JWhhzEZrEAockVV
Help the Authors find bugs faster by enabling Debugging when asked in your Github Issue (Bug Report).

Please help..

Thanks

**Comment by ljay79** [comment]
Yes, sorry.
The latest release had a bug.
I have just pushed a bugfix for this, and expext Google to approve and release it soon.

Bug is related to #102 and fixed with #106.

Very sorry for the inconvinience - was my poor testing on a rushed release.

**Comment by peter-cnp** [comment]
The issue is fixed. I'm back in business!

Thank you so much!

**Comment by ljay79** [comment]
I would appriciate honest rating and/or review within Google Marketplace on my Add-on. 🥇 👍

**Comment by Paul0975** [comment]
The issue is fixed. Appreciate your quick response.

Thanks
