### ISSUE TITLE
FEATURE REQUEST: Update data from Sheet back to JIRA

### ISSUE THREAD

**Issue by paul-lemon** [ljay79/jira-tools#108]
Thanks for sharing this add-on - really appreciated and very useful :)

I would like a feature that enables me to import jira issues, use a google sheet to capture data quickly and then post this updated data back to Jira, updating the fields in the original issues. 
**Example**

- The user imports a list of issues with a fixed set of fields from a JIRA query.
- The data is modified in google sheets by anyone with access to that sheet
- A script can then be called to update those fields changed in the spreadsheet back to JIRA. 
- Any fields not in the spreadsheet would not be updated in the JIRA issues
- The script would use the issue key to identity which issue in JIRA needs to be updated.

This would be useful as either a UI tool or a custom script which could be called from the google sheet.

I would be happy to help in the development if you feel this is a useful feature (and it is possible)

Thanks again for sharing your work.

**Comment by ljay79** [comment]
Hello @paul-lemon,

i do understand the use of updating data from google sheets back to Jira, however i must say, that i do not yet intend to add such functionality into this Add-On.
Its a whole other level of complexity which i do not see myself as capable of implementing it by myself.

I am very sorry to bring that to you, but i feel its better to admit my limitations of skills now, other than giving you false hope or promises...

PS: This project is open source and everyone is welcome to contribute. So who knows, maybe there is someone out there capable of contribution such functionality.

**Comment by paul-lemon** [comment]
Hi Jens,

I've been working on this feature here:-
https://github.com/paul-lemon/jira-tools
Its a work in progress but is working at a basic level, there's lots of work to do with fields from JIRA which are not straightforward strings.
To be able work on it I set up the code so I can use standard javascript tooling for unit tests and to use CLASP to deploy the code to GAS. 
Do you want to have a look and see if this is something you would be interested in merging at some point?

**Comment by ljay79** [comment]
Nive, will certainly take a look at it soon... Keep me updated

**Comment by paul-lemon** [comment]
Do let me know what you think.

**Comment by ljay79** [comment]
Hi. I did a first review and it looks like you know some JS programming.. :)
I like the preparation for local development with node and the deployment to GAS, i will have to check this out soon and probably adopt/implement this first.

For actual review of your feature i will need more time so i can actually run and test it. It looks promising, however looks also a little tricky with all the field handling, cant tell if thats the best approach :)  (WIP)

If you like, i would be happy, when you could extract just the unit testing and node development integration into a own branch and do a pullrequest when ready, so i could integrate it.

For the new feature, just do the same in a different branch and PR for more clearity and separation pls.

**Comment by paul-lemon** [comment]
Hi,

I understand a need to make the code change simpler and starting with the unit tests / build etc is a good idea.

I'm not able to separate the feature from the other parts in a straightforward way though. 

Would you be ok if I remove the new feature from the Menu so it is not visible to users but leave all the code in. Once you have looked at the way the code works for unit testing, clasp etc and checked the existing features are all ok we could then put the menu item back in and test the new feature?

I committed a version yesterday where the user interface is a lot cleaner and errors are reported to the user but there are still fields I would like to work better. I'd need your help with that I think.

Is there a better way to communicate and collaborate on this feature other than github issues?

**Comment by ljay79** [comment]
Hi @paul-lemon , i started a new branch for implementing the local development requirements, adopting it from your repo.

I have also added you as a contributor to my repo so you could directly interact with it by creating a new branch or updating (via PullRequest) existings.

- i tweaked just a few little things
- will review and add all these required node code blocks atm
-- how to run / test the code locally actually? Is that possible at all?
- the comment string i slightly tweaked as well before: _Require imports_ after: _Node required imports_

The new feature of yours, we should then start coding in a new feature branch on my repo (you can also continue on your repo and i will every now and then merge).
Once im done with the node,gasp implementation, i will checkout your additions in detail actually be able to safly run it in my GAS environment.

This way, i can now safely integrate the node parts first, then, when tested and ok, we can better share contributions and collaborative develop on the new feature(s).

BTW: Feel free to add your copyright or author tags where necessary...

**Comment by ljay79** [comment]
BTW: you can directly communicate with me via github [at] jens79 [dot] de

**Comment by paul-lemon** [comment]
Makes sense thanks! The change to the comments makes sense. I like it.

**Comment by ljay79** [comment]
> you can run tests with "npm test"
Yes ok, i figured that. I thought there is even a way of "running" some parts locally with node  hehe...  but i figure how would that ever work hehe.

The unit testing is nice enough.

So your usual workflow is; coding locally, deploy to GAS, test, repeat, ... push to git !?

**Comment by paul-lemon** [comment]
Yes, usual process is
1. TDD / Development (as much of the feature as I can is developed this way)
2. Deploy to GAS
3. Test within GAS and tweak code in the GAS interface (if easier)
4. Pull the code from GAS back locally and merge with SRC
5. Push to git

**Comment by paul-lemon** [comment]
Will do. I notice you are looking at issue #92 
You have mentioned solving it with this approach
"b) I will think of a convinient way of re-inserting entire filter results based on (last choosen filter) and the selected fields - something like a Quick-Menu with Favorites"
I like the sound of that as a user - I frequently re-use the filter in the same place on the spreadsheet.
If the user has the cell with with the text describing the filter selected, and that cell is directly above the heading titles I think it would be convenient and easy to use
![screen shot 2019-01-31 at 11 56 27](https://user-images.githubusercontent.com/2955356/52049915-4dd59d80-254f-11e9-801d-410f5286dd70.png)

This feature already reads those header fields and auto selects the best matching jira field so could have some useful code.

**Comment by ljay79** [comment]
Im currently looking more into a direction with almost no logic data inserted into cells as it has the user-fault level on high risk :)
Im looking into a reference storage - table meta data storage with all neccessary information to update a certail table range.

But yes, i see similarieties for part of the logic being able to use for your update feature as well or vise versa.

**Comment by paul-lemon** [comment]
Closing now https://github.com/ljay79/jira-tools/pull/169 is ready to be merged.

**Comment by ljay79** [comment]
Version 1.2.0 has been pushed to Google Marketplace with the new feature enabled for prodution use, with "beta" flag.

Pending Google's review.
