### ISSUE TITLE
Auto schedule "List issues from Filter"

### ISSUE THREAD

**Issue by vielhuber** [ljay79/jira-tools#110]
Hello!

Is it also possible to auto schedule "List issues from Filter"?

I'm familiar with Google Apps Script and can call functions based on a cron basis.

Am I able to call a function directly from your plugin?

Or is this something you have to add?

Thanks!

**Comment by christianhuening** [comment]
@vielhuber Is your intention with this requests to have your lists automatically updated? I would love that as well. I have favourite filters based on labels and thus would like them to be automatically updated in the Google Sheet as well.

**Comment by ljay79** [comment]
I think its duplicated to #92

I have a plan to add such functionality, but do not have a straight idea yet how. Please be patient.
