### ISSUE TITLE
SECURITY: Investigate use of OAUTH2 

### ISSUE THREAD

**Issue by paul-lemon** [ljay79/jira-tools#114]
The use of basic auth and storage of those credentials needs improvement.
OAUTH looks like a better option
https://developer.atlassian.com/server/jira/platform/oauth/
Worth an investigation to see if it's feasible and what impact there could be. Has this already been considered?

**Comment by ljay79** [comment]
Yes, this is basically why i have #23 created as a personal note :)

Therefore i would like you to comment in the #23 and have this closed as a duplicate.
