### ISSUE TITLE
JST_getTotalForSearchResult does not return "0"

### ISSUE THREAD

**Issue by rafal-lewandowski** [ljay79/jira-tools#117]
Apart from getting 0 for the query which does not return value, I'm getting #ERROR.

For example, for this:
=JST_getTotalForSearchResult("assignee = currentUser() and priority changed after startOfWeek()")
I'm getting that:
Error: [200] - {"respData":{"startAt":0,"maxResults":1,"total":0,"issues":[]},"httpResp":{},"statusCode":200} - JQL: assignee = currentUser() and priority changed after startOfWeek() (line 76).

How to get 0 as a result?

I do not want to use IFERR (IFERROR) as I need to distinguish the situations when the query was not properly built and when there are no results.

Thanks
Rafal

**Comment by ljay79** [comment]
Hi @rafal-lewandowski  this appears to be a bug, as you should not get the error message displayed as a cell value.
I will have a look into this soon and provide feedback. Thx for reporting.

BTW: Are you able to reproduce same behavior with different JQL queries which are syntactically correct and expect a simple "0" Results?

**Comment by rafal-lewandowski** [comment]
Hi @ljay79 ,
Thank you for the quick response!

Yes, I was trying a few different queries. Basically, when I pass the correct query when I expect "0" results, I get #ERROR like that:
![image](https://user-images.githubusercontent.com/42573985/51268903-5fe90500-19c1-11e9-88c9-25fa15e93b46.png)

In a case the query is wrong, I get #ERROR like that:
![image](https://user-images.githubusercontent.com/42573985/51268970-91fa6700-19c1-11e9-902e-3712f5594e6a.png)

**Comment by ljay79** [comment]
Thank you @rafal-lewandowski , i have just deployed a BugFix release which is rolling out through GAS.
I'll update you here, once Google confirmed the publishing process.

**Comment by ljay79** [comment]
Version 1.0.7 is now rolled out, you can check in the About dialog, if you have the latest version.
In case the same issue still persist, please reopen this one here.

**Comment by rafal-lewandowski** [comment]
Great!
It is working properly now.

Thank you!
