### ISSUE TITLE
Adding custom functions for additional fields

### ISSUE THREAD

**Issue by nezacec** [ljay79/jira-tools#131]
Hi, 

we are using your plugin for updating the Jira ticket statuses and we find it very useful. However, it would be great if we could extract some other info as well in the same way as Epic name is extracted with this function:
`JST_EPICLABEL("JST-123")`

We would like to extract at least a due date, for example:
`JST_DUEDATE("JST-123")`

Or, if it can't be done this way, by entering the Jira field id as well, like this:
`JST_GET("JST-123", "duedate")`

If it would be done this way, I guess we could extract also other simple fields like assignee?

Thank you for your work and answer!
Neza

**Comment by ljay79** [comment]
Thx @nezacec for filing this ticket.

Did you tried using _JST_search()_ for this purpose?

```markdown
=JST_search("issue = JST-123"; "key,duedate")
```

**Comment by nezacec** [comment]
Great, works this way for due date:
`=JST_search("issue = JST-123"; "duedate")`
but I can't get it to work for the second field like you suggested:
`=JST_search("issue = JST-123"; "duedate, status")`
In this case it just writes the word "status" in the second column and not actual status (or key or any other field id)

**Comment by ljay79** [comment]
Remove the spaces, do just `"duedate,status"`.
Will take a note and make this function accepting spaces in the comma list...

**Comment by nezacec** [comment]
That's great, thank you!
