### ISSUE TITLE
UpdateIssue: Error on key values

### ISSUE THREAD

**Issue by ljay79** [ljay79/jira-tools#135]
Collecting bugs of _Update Issue (Beta)_ feature of type issue key data format.

Error: `[TP-6] Component/s: data was not an array,` when updating Jira standard field `Component/s` with a comma list of strings.

Request:
```markdown
{payload={"fields":{"summary":"Test Story 1 - appended2","labels":["test"],"components":"","description":"Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum "},"update":{"comment":[{"add":{"body":"Updated by Jira Sheet Tools https://github.com/ljay79/jira-tool"}}]}}}
```

Response:
```markdown
Code: 400.0, ResponseHeaders: {Transfer-Encoding=chunked, Server=Atlassian Proxy/1.13.6.2, X-Content-Type-Options=nosniff, Connection=close, Date=Wed, 06 Feb 2019 18:35:20 GMT, atl-traceid=xxxxxx, Strict-Transport-Security=max-age=315360000; includeSubDomains; preload, x-seraph-loginreason=OK, Cache-Control=no-cache, no-store, no-transform, x-ausername=xxxxxx, x-arequestid=xxxxxx, Timing-Allow-Origin=*, x-aaccountid=xxxxxx, Set-Cookie=atlassian.xsrf.token=B2DC-xxxxxx; Path=/; Secure, X-XSS-Protection=1; mode=block, Content-Type=application/json;charset=UTF-8}, httpResponse: {"errorMessages":[],"errors":{"components":"data was not an array"}}
```

**Comment by paul-lemon** [comment]
Thanks - components isn't something I've tested.

**Comment by paul-lemon** [comment]
Sample code from https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/#editing-an-issue-examples

`curl \
   -D- \
   -u charlie:charlie \
   -X PUT \
   --data {see below} \
   -H "Content-Type: application/json" \
   http://localhost:8080/rest/api/2/issue/QA-31`

`{
    "update" : {
        "components" : [{"set" : [{"name" : "Engine"}, {"name" : "Trans/A"}]}]
    }
}`

**Comment by ljay79** [comment]
Yes, this will become a very tidy and tricky task anyway soon. All these different field definitions with their expected in/out -put formats. It applies basically to anything beside integers and strings.

**Comment by paul-lemon** [comment]
I've tested all of the built in JIRA fields with the new feature. These are the error messages when updating. This needs some review to work out which ones can be left and which ones can be fixed :- This is the error mesage

Field 'watches' cannot be set. It is not on the appropriate screen, or unknown., 
Creator: Field 'creator' cannot be set. It is not on the appropriate screen, or unknown., 
Time Spent: Field 'timespent' cannot be set. It is not on the appropriate screen, or unknown., 
Original Estimate: Field 'timeoriginalestimate' cannot be set. It is not on the appropriate screen, or unknown., 
Project: Can not instantiate value of type [simple type, class com.atlassian.jira.rest.api.issue.ResourceRef] from JSON String; no single-String constructor/factory method, Reporter: Field 'reporter' cannot be set. It is not on the appropriate screen, or unknown., Σ Time Spent: Field 'aggregatetimespent' cannot be set. It is not on the appropriate screen, or unknown., Resolution: Field 'resolution' cannot be set. It is not on the appropriate screen, or unknown., Environment: Field 'environment' cannot be set. It is not on the appropriate screen, or unknown., Remaining Estimate: Field 'timeestimate' cannot be set. It is not on the appropriate screen, or unknown., 
Σ Remaining Estimate: Field 'aggregatetimeestimate' cannot be set. It is not on the appropriate screen, or unknown., Resolved: Field 'resolutiondate' cannot be set. It is not on the appropriate screen, or unknown., Votes: Field 'votes' cannot be set. It is not on the appropriate screen, or unknown.,

**Comment by paul-lemon** [comment]
I've either fixed the issues or marked the fields as readonly.
From now on we can raise issues for individual fields. Closing this now
https://github.com/ljay79/jira-tools/pull/169
