### ISSUE TITLE
Screen shots for update sheet functionality

### ISSUE THREAD

**Issue by paul-lemon** [ljay79/jira-tools#137]
Maybe a video too.

**Comment by paul-lemon** [comment]
![screen shot 2019-03-05 at 09 31 03](https://user-images.githubusercontent.com/2955356/53837132-2a5ca300-3f92-11e9-90fb-435c211e0e3e.png)
![screen shot 2019-03-05 at 21 59 39](https://user-images.githubusercontent.com/2955356/53837142-36486500-3f92-11e9-9ce4-c98c8a515d10.png)
![screen shot 2019-03-05 at 21 57 43](https://user-images.githubusercontent.com/2955356/53837394-c4245000-3f92-11e9-9bb3-42dda1d3969d.png)

![screen shot 2019-03-05 at 21 58 00](https://user-images.githubusercontent.com/2955356/53837388-bec70580-3f92-11e9-81a6-e7c6a4a4e299.png)
![screen shot 2019-03-05 at 22 00 28](https://user-images.githubusercontent.com/2955356/53837156-3ba5af80-3f92-11e9-8775-61cf9442ab99.png)

**Comment by paul-lemon** [comment]
Screen shots (also shows due date and labels working! ;) )

**Comment by paul-lemon** [comment]
^ @ljay79 - that enough?

**Comment by ljay79** [comment]
I have used following screenshot (yesterday).
Im sadly limited to 4 elements. I would like to replace one more with a nice video.. But its not urgent :)

![live-04](https://user-images.githubusercontent.com/12184976/53879107-ead39c80-400d-11e9-93b2-171431d39803.png)
