### ISSUE TITLE
getting error when insert > list issues from filter

### ISSUE THREAD

**Issue by ashishsrivastava02** [ljay79/jira-tools#14]
TypeError: Methode "indexOf" von null kann nicht aufgerufen werden.

**Comment by ljay79** [comment]
Thanks for the feedback.
Somehow i broke the setting for the default jira issue columns during one of the past changes.

I have applied a proper fix now with commit 9d7f50ba0c2c4e8f980d3527aa8a778ca06cb72d .
Please watch out for my next release to the google app store. 
(will update you here later on)

Im trying to add some Jira Server version compatibilities with the next release.

**Comment by ljay79** [comment]
I have just released the new version (https://github.com/ljay79/jira-tools/tree/v0.14.0) to GAS.
It should be available shortly in the Google Sheet Addon Store (GAS).
Your installed add-on would update fully automatically.

(In case you are using Jira Server and not OnDemand)
When new update available (v0.14.0), please go into: _“Add-ons > Jira Sheet Tools > Settings”_
and press "SAVE", this will then trigger the new config for Server vs. OnDemand.

Note: You can check what version is currently available in your google sheet, by open _"Add-ons > Jira Sheet Tools > About"_ from within google sheet .

**Comment by ljay79** [comment]
Hi @ashishsrivastava02 

was i able to solve your issue? Is it working for you now?

**Comment by ashishsrivastava02** [comment]
HI,

Thanks. it is working well for me now.

**Comment by ljay79** [comment]
awesome
