### ISSUE TITLE
Use consistent casing in the naming of folders and modules/classes in the codebase

### ISSUE THREAD

**Issue by paul-lemon** [ljay79/jira-tools#141]
there is a mix of camel case with a leading lowercase letter e.g.
"jiraAPI"
"Dialogs"
"Storage"
"UserStorage"
"userManager"
This looks inconsistent and untidy and has caused issues where the require files on a Windows PC were inconsistent.
I suggest using a capital first as per Java standards - upto you @ljay79

**Comment by ljay79** [comment]
Hmm... i will do a little research which/what standard would best apply to this project.

Initially i starting apply my logic:
regular functions and libraries start with a lower case, and Classes start with upper case... But i fully agree, its inconsistent.

From my PHP projects, it would be basically; all Classes start with upper case, all others with lower...

**Comment by paul-lemon** [comment]
I've never loved that PHP convention tbh! :)

Now Clasp allows the use of folder perhaps a folder structure could help navigation around the growing code base. It took me a while to find stuff e.g.
```
Code.js - builds the menu and any other lifecycle event handling
actions/
  menu/
       doSomethingFromTheMenu.js (use a name that corresponds to the menu text)
  functions/
       doFunctionFromSpreadsheet.js (use a name that corresponds to the function)
  callbacks/
       functionCalledFromHTML.js (use the name of the function called from "google.script.run")
views/
     view1.html
     view2.html
controllers/
     ClassA.js - classes which do some work (e.g. IssueTransitioner)
services/ - code which interfaces with external services like JIRA / Google storage
     jira/
     gas/
```

**Comment by paul-lemon** [comment]
Also meant to suggest using the naming of ".js" for files - makes it easier in editors and with defaults in things like require(""). 
Clasp actually renames the downloaded "gs" files as "js" so its unnecessary really...

**Comment by ljay79** [comment]
Hmmm...  to many folders dont make it better :)

Lets try to keep it simple.
For the beginning i see obvious use for folders:
_./view/_
_./lib/_
_./customFunctions/_

Folders are actually a development env benefit only. GAS and the GAS editor do not support any folders at all.

The part with _.js_ vs _.gs_ i like. If clasp will take care of this anyway, i dont see a reason of keeping _.gs_ extensions in the repo.

**Comment by paul-lemon** [comment]
Looks good. I'm happy with those folder suggestions. I like the model thoughts.

The reason I suggest "actions" or something similar is it gives you (the developer) a clear place to start with where the functionality is. 
The suggestion for "customFunctions" is good as it is obvious if you are working on a new or existing function where the code belongs. 
I struggled to see where the menu actions lived and also where to put the callback functions from the dialogs.
I think it would be a benefit as I cant see in your suggestion where I would put those functions. As its similar to an MVC pattern where you have a method that deals with a HTTP request I thought a similar folder pattern would work.

**Comment by paul-lemon** [comment]
".gs" vs ".js" isnt critical and I'm happy either way. This project uses JS only
https://github.com/gsuitedevs/apps-script-oauth2

**Comment by ljay79** [comment]
> ".gs" vs ".js" isnt critical and I'm happy either way. This project uses JS only
> https://github.com/gsuitedevs/apps-script-oauth2
Yes but this specific one is a libary for importing into multiple kind of projects while all actual app scripts a with a _.gs_ extension.

As you are fine with either way, i really like to keep _.gs_ at least for now.

**Comment by ljay79** [comment]
> customFunctions
Not sure if i got you right, its supposed to be the place for public GAS custom functions (https://developers.google.com/apps-script/guides/sheets/functions).

Regarding UI callbacks from sidebar or dialogs, you're right. This isnt well accomodated yet.
It could be concidered a controller with multiple actions (methods) or just as _./helpers_ .
In general such callbacks do act as a helper only: taking input, calling actual functionality, returning values to HTML/UI.

I just cant associate the name _./actions_ with anything im confident with :)
You call?!

**Comment by paul-lemon** [comment]
I've found "helpers" to turn into a bit of a dump for anything and everything unless its well defined (e.g. view helpers). All code is "helpful" so lots of things can end up there.

I like the idea of all functions which are executed by a user action or a spreadsheet action being in a single place. They are the entry route into the code base for a piece of functionality. As I started to work out what was going on in the code base that was what I had to find to understand the flow of execution.

How about:-
controllers/
       updateIssues.gs <-- named after the overall feature
          -- then inside use a convention of "menuDoSomething" for functions called from the menu and "callbackDoSomethingElse" for functions called from "google.script.run"

"controllers" is consistent with MVC terminology so should be easier for new developers to find their way around.

**Comment by ljay79** [comment]
Almost fully agree.

Lets do `controllers` and the naming convention for _menu_ and _callback_ (maybe just: _cb_ for callback) prefix for filenames.
As long we dont have more than 10 files inside `controllers`, how about no subfolders atm? :)

If ever we need subfolders to organize more than 2 or 3 menu/callback files, i dont like to call them after a filename.

**Comment by paul-lemon** [comment]
Sorry I wasnt clear I was trying to say:-

**File Structure**
```
controllers/
       updateIssues.gs <-- named after the overall feature
       anotherFeature.gs
       etc.gs
```
in each file e.g. **updateIssues.gs**
```
/*
* Functions for updateIssues feature menu and callbacks from Google Sheets
*/
function menuUpdateIssues() {
  // do stuff when the menu item is clicked
}

function menuAnotherThingForUpdateIssues() {
  // do stuff when the menu item is clicked
 // unlikely a feature will have two menu options but just for illustration.
}

function callbackProcessIssues() {
  // do stuff from a callback from google.script.run
}
```

**Comment by ljay79** [comment]
Yep,  I like this more.

**Comment by ljay79** [comment]
```markdown
/config/ <- the environment configuration stuff where necessary
    /production/
        environmentConfig.gs
    /test/
        environmentConfig.gs
/views/ <- any HTML files
    /dialogs/ <- all the dialogs HTML
         settings.html
         about.html
    /sidebar/ <- all the sidebar HTML (coming)
        fieldMap.html
/libs/ <- any generic abstract and reusable code like `jsLib` and other generic functions / classes
    jsLib.gs
    debug.gs
/customFunctions/ <- all GAS custom functions
/controllers/ <- javascript models
        /status/ <- JIRA status transitioning models
    updateIssues.gs <- feature with menuXXX and callbackXXX methods
    otherFeature.gs
    Search.gs
    ...
/api/ <- code which interfaces with external services like JIRA / Google APIs
    JiraApi.gs
    Storage.gs
```

Would that be the summary of all?

**Comment by paul-lemon** [comment]
Looks good - my last thought would be on "customFunctions" - could that get mixed up with being "custom functions' in the code base to do stuff versus the custom functions for the spreadsheet?

**Comment by ljay79** [comment]
At this moment, the actual GAS custom functions are only short and light weight. Would cause overhead splitting them up into individual files. So i would actually keep the current file named _customFunctions.gs_ and not have a folder of same name.

**Comment by paul-lemon** [comment]
When working on refactoring in PR's https://github.com/ljay79/jira-tools/issues/135 and https://github.com/ljay79/jira-tools/issues/145 I came to a clearer view of what I think I need to do to refactor the code in the "Update Jira" feature and how it fits in.
This is specifically around the "models' used to represent JIRA objects in the application and how they should fit into the codebase and interact with JIRA.
See what you think and let me know.

1. I think we missed / confused models and controllers in the directory structure.
I *think* we need /controllers for placing code that interacts with the UI and spreadsheet ie. where the "actions" from menus and callbacks go - also with helper code (private methods) to extract and insert data into the spreadsheet in response to those actions

I *think* we need a models object the has the internal application representation for 
-- a jira entity which the controllers can use for CRUD operations on the REST API (e.g. Issues / Fields etc)
-- other entities which the application needs e.g. UserSettings.

The models should abstract from the application the interaction with the underlying services and APIs
So I think this works?
```
/config/ <- the environment configuration stuff where necessary
    /production/
        environmentConfig.gs
    /test/
        environmentConfig.gs
/views/ <- any HTML files
    /dialogs/ <- all the dialogs HTML
         settings.html
         about.html
    /sidebar/ <- all the sidebar HTML (coming)
        fieldMap.html
/libs/ <- any generic abstract and reusable code like `jsLib` and other generic functions / classes
    jsLib.gs
    debug.gs
/customFunctions/ <- all GAS custom functions
/controllers/ <- controllers 
    updateIssues.gs 
    otherFeature.gs
    Search.gs
    ...
/models/
        /jira/ 
           Issue.gs - Internal Model and CRUD operations on Jira Issue(s)
           Fields.gs - Internal model for accessing fields (including Epic Field etc)
        /application/
            UserSettings.gs - Model for saving user settings
   
/api/ <- code which interfaces with external services like JIRA / Google APIs - called by models.
    JiraApi.gs
    Storage.gs
```

**Comment by paul-lemon** [comment]
@ljay79  - how does the above look?

Thinking some more about this I think the folders can be used to enforce decoupling.

I propose that code in each of these folders has a discreet set of responsibilities and we put the output of this discussion in an markdown file e.g. CodeStandards.MD in the route



|File / Folder | Responsibilities |
|------------|-----------|
|Code.gs | Initialises menu and GAS lifecycle events|
|controllers | One file per feature. Interacts with the sheet, models and updates views |
|views | HTML files for the UI in the Google sheet |
|models | Entities for the entities e.g Jira Objects, User preferences. Interacts with underlying Google services and Jira API |
|libs | Generic JS Libraries used as a dependecy only - does not interact with any other code |
|api | Service layer to interact with external services e.g. JIRA. used as a dependency only does not interact with any other code *except* libs |

```
/config/ <- the environment configuration stuff where necessary
    /production/
        environmentConfig.gs
    /test/
        environmentConfig.gs
/views/ <- any HTML files
    /dialogs/ <- all the dialogs HTML
         settings.html
         about.html
    /sidebar/ <- all the sidebar HTML (coming)
        fieldMap.html
/libs/ <- any generic abstract and reusable code like `jsLib` and other generic functions / classes
    jsLib.gs
    debug.gs
/controllers/ <- controllers 
    updateIssues.gs 
    otherFeature.gs
    search.gs
    customFunctions.gs <- all GAS custom functions
    ...
/models/
        /jira/ 
           Issue.gs - Internal Model and CRUD operations on Jira Issue(s)
           Fields.gs - Internal model for accessing fields (including Epic Field etc)
        /application/
            UserSettings.gs - Model for saving user settings
   
/api/ <- code which interfaces with external services like JIRA / Google APIs - called by models.
    JiraApi.gs
    Storage.gs
```
 
@ljay79  - I propose starting a branch with CodeStandards.MD and putting all of this in so we can collaborate and its there for any other contributors.

**Comment by ljay79** [comment]
Ok sure, go ahead with this.
Just a reminder again, do add to many subfolders yet if this will only organize a hand full of files.
Proper filenames is suitable enough.
Ie: for the subfolders in _views_ and in _models_ .
As long there are not more than ~5 files, i dont think there is a big benefit of adding subfolders with each 1 or 2 files in it.

**Comment by paul-lemon** [comment]
Good point about the folders. Its all pretty sparse now so it's hard to tell. Is it ok if I follow the pattern and then we review?

**Comment by ljay79** [comment]
sure :)

**Comment by paul-lemon** [comment]
Added the code standards MD file in https://github.com/ljay79/jira-tools/pull/157
Closing this issue (although the standards are not yet applied to all of the code.
