### ISSUE TITLE
Google's app script review

### ISSUE THREAD

**Issue by ljay79** [ljay79/jira-tools#144]
Latest add-on release on GAS got rejected with following reason(s).

> Please correct the add-on name.  Remove the Jira from it. You can call it Tools for Jira. Please correct it on all the add-on 

No idea, why they complain about the naming all the sudden, after already more than 40 releases of the same.
So, now we must find new name apparently :(

Any suggestions?

**Comment by paul-lemon** [comment]
That's frustrating after forty releases.
I guess Jira is really Atlassian's copyright so I guess Google worry it may look like this Add-On is from Atlassian and not an Open source community add-on 

Some thoughts
- do you need to be clear this is for Google Sheets in the title - I guess not because it's in the Google Add-Ons marketplace and labelled Sheets already?
- I think you need Jira in the title to explain what it does so if all Google allows is "for Jira", I think you should take that
- Is "Tools" the right name would a user know from the title alone what it does.
   - "Integration for Jira"?
   - "Connector for Jira"?

Looking at the marketplace alot of Add-On developer have opted for names that just explains what the add-on does

![screen shot 2019-02-09 at 12 02 31](https://user-images.githubusercontent.com/2955356/52519890-be24a300-2c62-11e9-93e9-c97c5aac2c89.png)

**Comment by ljay79** [comment]
"Collaboration tools for Jira"

**Comment by paul-lemon** [comment]
Collaboration was the reason I wanted to use the add-on. I think the add on is a few features off that truly make that possible. Sheets are such an easy way for multiple people to quickly see and change things whereas the Jira interface makes that hard. Being able to pull the data from (and push it back to) Jira will make collaboration easier.

I think your add-on does other things to - easier reporting etc. So maybe collaboration doesn't cover that?

The other thing to consider is that "collaboration" can mean so many things it may not be as clear as some of the titles above.

I wonder if Google may accept other uses of Jira in the title e.g.
"Integrate Jira Issues with Sheets"
I think that does say exactly what your add-on does.

**Comment by ljay79** [comment]
Yep, most samples do only a specific (little) purpose. My add-on does already a few different things all together with Jira.

"Integrate Jira Issues with Sheets" is something to think about.

**Comment by ljay79** [comment]
Before it makes sense to really for forward with refactoring and enhancements, i like to get the current master release to GAS.

So we need a new name first, release and then going back to normal business.
(Im really pissed about this request from Google) damn it...

Most GAS add-ons concentrate on a single specific task, our here does kind of Reporting but als (new) Editing, thats difficult to incorporate into a single short title.

There would be actually a consideration of splitting it into 2 individual add-ons, but im not sure atm if this will help improve user expirience...

Anyway, here are my current add-on title ideas:

- Report & Update Jira Issues
- Build Reports and Update Issues from Jira
- Connect Jira with Sheets
- Reporting and Edit for Jira
- Integrate Jira Issues with Sheets
- Collaboration tools for Jira

**Comment by paul-lemon** [comment]
Makes sense to delay those code PRs - I had some time this weekend and I just needed to test that last one on JIRA with components hence it being opened this weekend. I'm done for now.

I like these in this order 
* Build Reports and Update Issues from Jira <-- you can't use this one yet though.
* Connect Jira with Sheets
* Integrate Jira Issues with Sheets
* Collaboration tools for Jira

**Comment by ljay79** [comment]
We must keep in mind, its also the 1. menu item in any spreadsheet: "Add-ons" -> "xxxx".
Many of the samples you found, and myself, are mostly custom functions i believe...
will do some more research tomorrow...

**Comment by ljay79** [comment]
How about:

**Project Aid for Jira** - _Create reports and manage Jira projects_

**Comment by paul-lemon** [comment]
Sounds good.
I'd be careful about managing Jira "Projects" - I dont think there is enough functionality in there yet to make that claim 
How about
**Project Aid for Jira** - _Create reports and manage Jira issues_

**Comment by ljay79** [comment]
Your'r right.

So we have a new add-on name:

**Project Aid for Jira** - _Create reports and manage Jira issues_
