### ISSUE TITLE
Affected Version not Displayed in JST_search Results

### ISSUE THREAD

**Issue by zettajim** [ljay79/jira-tools#161]
Tried including "versions" (per "Jira Field Map"), "affectedVersion", "affectsVersions" but not getting the value for Affects Version/s from the tickets.

Thank you for a fantastic tool!

**Comment by ljay79** [comment]
Hi @zettajim i will check this asap

**Comment by ljay79** [comment]
Thanks for pointing out that bug.
I have applied a BugFix and pushed a new release to the marketplace currently awaiting for google's review and approval.

As soon you see the version `v1.1.1` in the add-ons "About" dialogs, you have the newest bugfixed version and the mentioned fields should properly show up.

I'll keep this issue a few more days open in case you have negative feedback.

**Comment by ljay79** [comment]
Fixed / Closed
