### ISSUE TITLE
Improve UI - Unsupported fields for Issue Update

### ISSUE THREAD

**Issue by ljay79** [ljay79/jira-tools#168]
During the Issue update field selectio, there are quite a few which are not yet supported due to data type expected for the API during a update.
For such fields, we should deactivate the checkbox; grey them out; or indicate it in any way to the user.
Similar to the UI of "Configure Custom Fields".

![jst-issueupdate-fields](https://user-images.githubusercontent.com/12184976/53686003-4fe37580-3d22-11e9-8125-ad99e453c4ab.jpg)

![jst-configure-custom-fields](https://user-images.githubusercontent.com/12184976/53686004-5376fc80-3d22-11e9-98b1-69fc2913a847.jpg)

**Comment by paul-lemon** [comment]
Done in https://github.com/ljay79/jira-tools/pull/169/commits/3d78ff0df251322e0a637ff40b7da80de2e45e81
When a user selects a field with (Read only) in the dropdown it will be deselected and grayed out when then click "Update Jira Issue(s)"
![screen shot 2019-03-02 at 21 05 05](https://user-images.githubusercontent.com/2955356/53686988-f03f9700-3d2e-11e9-9184-4de69fd0a7e8.png)

**Comment by ljay79** [comment]
Awesome. Even I didn't expected that change pre release.
