### ISSUE TITLE
Update Jira Issues: Supported fields - Due & Start date

### ISSUE THREAD

**Issue by ljay79** [ljay79/jira-tools#171]
New feature "Update Jira Issues" does fail on certain jira fields due to their expected format transmitted to the API during IssueUpdate.

Field: 
_Due_ & _Start date_

Error:

> Due date: Field 'duedate' cannot be set. It is not on the appropriate screen, or unknown.,

> {"errors":{"duedate":"Field 'duedate' cannot be set. It is not on the appropriate screen, or unknown."}}

> Start date: Field 'customfield_11131' cannot be set. It is not on the appropriate screen, or unknown.,
> {"errorMessages":[],"errors":{"customfield_11131":"Field 'customfield_11131' cannot be set. It is not on the appropriate screen, or unknown."}}

**Comment by paul-lemon** [comment]
Can't reproduce this either.
This may be down to the individual permissions on your jira instance so can you check that you can update the duedate field from the JIRA edit screen and in the current status of the ticket.
Jira admins can set quite fine grained permissions on fields so that may be the cause.

**Comment by ljay79** [comment]
I am the one and only admin in our Jira Cloud Instance.

What format is expected to be entered in the sheet cell for _Due date_ and/or _Start date_ ?

**Comment by ljay79** [comment]
Ok, appears to work. "Due date" as really not part of the Issue Screen for this partical test project.
Works on a different one as expected.
Start Date, i couldnt confirm yet but according to error message its a jira screen type dependency and not an Add-on format/scheme issue.

I think we therefore can close this issue ?

**Comment by paul-lemon** [comment]
Good to close. I think the messaging may need to improve the error from
JIRA API is not easy to understand - we should monitor feedback from users

**Comment by dhruvalShahTatvasoft** [comment]
Not able to add 'duedate' in Jira Issue Rest API.
Getting same error :
{
    "errorMessages": [],
    "errors": {
        "duedate": "Field 'duedate' cannot be set. It is not on the appropriate screen, or unknown."
    }
}

If any one able to help please?

**Comment by ljay79** [comment]
@dhruvalShahTatvasoft please verify the "duedate" field is part of the "Issue Screen" within Jira for the respective project.
Each project in jira can have custom definitions of available, allowed, editable issue fields.

**Comment by johns10** [comment]
I'm on a completely different library. I was able to get it to take due date by enabling it on the screen for the project. HOWEVER, I cannot get start date to work the same way.
