### ISSUE TITLE
Update Jira Issues: Supported fields - Sprint

### ISSUE THREAD

**Issue by ljay79** [ljay79/jira-tools#172]
New feature "Update Jira Issues" does fail on certain jira fields due to their expected format transmitted to the API during IssueUpdate.

Field: 
_Sprint_

Error:

> {"errorMessages":[],"errors":{"customfield_11121":"data was not an array"}}

**Comment by paul-lemon** [comment]
Will check this later

**Comment by paul-lemon** [comment]
I am testing on JIRA v7.6.3 server side API

I can't reproduce this. I can assign an issue to an existing or future sprint.
I have only tested with a single sprint.
This is the payload when doing so
`fetchArgs: {payload={"update":{"comment":[{"add":{"body":"Updated by [Project Aid for Jira|https://github.com/ljay79/jira-tools]"}}]},"fields":{"customfield_11090":5671}}}`


customfield_11090 is the Sprint field

This is the schema for the sprint field in the Jira Instance I am testing against.
```
{schema={custom=com.pyxis.greenhopper.jira:gh-sprint, type=array, items=string, customId=11090
    }, navigable=true, orderable=true, custom=true, name=Sprint, clauseNames=[cf[
        11090
      ], Sprint
    ], id=customfield_11090, searchable=true
  },
```

**Comment by paul-lemon** [comment]
I think anyway while users have to enter the integer ID of the sprint this field should be disabled.

**Comment by ljay79** [comment]
A user would have to enter the ID at the moment? I tried with the corresponding string value.
So its basically expected to fail in my case?

**Comment by paul-lemon** [comment]
Yes thats expected but unsatisfactory behaviour for the user.
The JIRA API only accepts the integer sprint ID 
Retrieving the list of sprint names and IDs is not straightforward at all hence
https://github.com/ljay79/jira-tools/issues/150

We have options
1. Document the need for an ID (release needed?)
2. Remove the sprint field for now until (or if) https://github.com/ljay79/jira-tools/issues/150 is resolved. This is a simple change in the getReadonlyFields function in IssueFields.gs to make it readonly but will require a release.

**Comment by ljay79** [comment]
Yeah i forgot about #150 . I think we can close this issue then in favor for #150 .
