### ISSUE TITLE
Exceeding quota for calls to Properties get

### ISSUE THREAD

**Issue by paul-lemon** [ljay79/jira-tools#177]
** Provide a general summary of the issue in the Title above **
Stackdriver calls show alot of logging for errors relating to calls to exceeding quotes on calls to Properties Get
These errors when exceeding the quota will cause an error for the user and make the add-on look buggy
** Provide a more detailed information of the issue **
Logging calls to UserStorage.get (which calls the property service directly) 
I can see between 10 to 111 calls per dialogue or action in a dialogue
By storing the properties in a single JSON document we can reduce that to 1.
Something like this:-
```
var UserStorage = {
  _appStorage: false,
  counter:0,
  userProps: null,
  
  getValue: function(key) {
    if (userProps == null) {
      userProps = this._getAppStorage().getValue("userprops");
    }
    return userProps[key];
  },
```

Work would be need to done on the initialisation of the 'userprops' object etc.

**Comment by paul-lemon** [comment]
In case its not clear I mean if the Add on stores all the settings in one JSON object in the User Properties instead of storing each one individually the number of calls will drop to about 10-20% of the current number of the calls. Currently each separate property requires a separate call to the service.

**Comment by paul-lemon** [comment]
@ljay79 - I can work on this later - i think its important for release 1.2.1 - agree?

**Comment by ljay79** [comment]
I think, raping the storage design of google app script isnt the best approach to solve this.

I prefer a more analytical approach first.
Is there actually a problem for regular users?
What is causing the quota limit errors seen in stackdriver logs? (regular users or some corrupted sheets,add-on, side-effects,...)

The Property storage is used by our add-on exactly the way it is designed for and one would expect it to be used.
The individual storage limitations (ie bytes per key, total number of keys,..) are limiting the use of the storage in a way you propose to use it.

Im fine with further investigation, benchmarking, error research etc.. but i dont like the idea of messing with the storage pattern by trying to sqeeze JSON objects into strings and then into the storage. This will add a lot more complexity in error and type handling in the code which shouldnt be necessary.

Some facts:
Google Quotas for "Properties read/write"
Consumer (e.g., gmail.com): _50,000 / day_
G Suite Basic / Gov: _500,000 / day_

Sample Usage:

1. Inserting issue list with 16 issues (13 columns/fields)
 - including call to dialog, fetching filters etc
 - Resullt: 19 hits on _Properties_ (read/write)
 
2. Open Settings Dialog: 10 hits
3. Open Jira field map:  10 hits
4. Open configure custom field: 10 hits

Assuming worst case; a regular Consumer with just a free gmail account has a limit of 50.000 read/writes on the Properties per day.
Can you estimate how many interactions it requires in a real world scenario to hit this limit...

**Comment by paul-lemon** [comment]
![screen shot 2019-03-08 at 12 06 03](https://user-images.githubusercontent.com/2955356/54025376-a1648800-419a-11e9-92d9-78370c494248.png)
1.3m errors in the last 30 days?
Each one of these is an exception to the user

**Comment by paul-lemon** [comment]
The number of users its affecting is not high though - although I don't know the number of users of the add on.

**Comment by ljay79** [comment]
Keep in mind, it includes our develop cells as well.
And apparently they are a few installations causing most of these...

**Comment by paul-lemon** [comment]
Yup - makes sense - I've updated the Storage class to the latest version and that includes some code to prevent repeated hits for values which are null - that may improve the behaviour in those rogue sheets.
I'll close
Thanks @ljay79 :)
