### ISSUE TITLE
Adding Column such as Epic link

### ISSUE THREAD

**Issue by MHLarouche-aldo** [ljay79/jira-tools#18]
Hi! 

I'm unable to add the Epic Link column or choose it from the list. Is it possible? I was hoping the workaround (adding a column, writing "Epic Link" the exact same way as Jira does and then refreshing the data) would work.

Can you help? Thank you!

**Comment by ljay79** [comment]
Hi. Thanks for your feedback.
Currently this add-on does not support "Epic link" but i will consider adding it.

**Comment by MHLarouche-aldo** [comment]
It would be very useful! Our business stakeholders will take ages before using Jira as their primary tool. Spreadsheet is the way to communicate to them the % progress for each desired features. 

Isn't there another workaround until it gets (hopefully) added? 

Thank you!

**Comment by ljay79** [comment]
Hi @MHLarouche-aldo i have checked the ability to include a Epic Link, and while reviewing the documentation i remembered why i didnt included it from the beginning.

Jira "Epic Link" simply put is a custom field inside jira and not a standard field i can assume to fetch from any instance of Jira the same way.

At this stage i have to tell you, i wont be able to add this issue field to the add-on.
It would require a different approach of fetch any kind of fields individually for the users Jira instance - which i have in planing for a later version after i have added worklog reports.

Sry i couldnt help this time

**Comment by MHLarouche-aldo** [comment]
Epic Link or Epic Name..?

**Comment by ljay79** [comment]
its basically the same.
To be more precise, by default the Epic is a regular jira issue link of type epic which has a name, url/link and more details.

If you are familiar with RESTapi feel free to investigate my code, im always happy for contributions.

**Comment by MHLarouche-aldo** [comment]
thank you!!

**Comment by ljay79** [comment]
PS: I feel your pain with acceptance of Jira for the stakeholders, have/had same issues for long.
Atm i can not think of a short time solution to add this field into the list.

However, maybe it helps as workaround, you could add a regular issue list into your sheet, then manually add another column, add the Jira issue Key of the Epic by yourself. And with "Jira Sheet Tools -> Refresh Ticket Data" you can keep this table updated - at least the issue status next to the key can be updated this way.

Other option for now, create custom filter per individual Epic then create sheets for each of the Epic, so the entire table list of issues is for 1 specific Epic only.

**Comment by MHLarouche-aldo** [comment]
yeah, I was thinking about that second option you recommend! 

Thanks again, I'm close to fulfilling their needs... thank you!
