### ISSUE TITLE
time report: not all users are dislpayed

### ISSUE THREAD

**Issue by Blondstar** [ljay79/jira-tools#183]
when creating a time report, and wanting to select a user not all users are displayed 

### Steps to reproduce
** Provide a set of unambiguous steps to reproduce this bug include code, if relevant **
1.go to time report
2.click to creaet report
3.select user

### Expected result
** Tell us what should happen **
1. all user in the system are displayed and possible to select

### Actual result
** Tell us what happens instead **
1. only the first users are displayed. (if there is too much users and not all can be displayed an option could be to enter the user ID or something else

**Comment by rokkbert** [comment]
Could be the same issue as #85 . The version here is 1.2.1, so even 250 users might not be enough. Can this be configured somehow?

**Comment by ljay79** [comment]
Im working on an improvement for the UI allowing such autocomplete in the dialog which then allows more than a handfull of entries (users).

Just for curiosity; about how many users (real world scenario) are we talking about?

**Comment by Blondstar** [comment]
I have no idea.... I only got to the letter D....
I think auto complete could also be problematic since some users are not allowed to use the auto complete and @ function (this is a global permission in jira)
maybe allowing to enter the username would be an easy solutiin...
Thanks!

On Mar 21, 2019 13:02, Jens <notifications@github.com> wrote:

Im working on an improvement for the UI allowing such autocomplete in the dialog which then allows more than a handfull of entries (users).

Just for curiosity; about how many users (real world scenario) are we talking about?

**Comment by ljay79** [comment]
Thx for the valued input.
I cant think of a reason, a user would create timereports for users he isnt allowed to find via autocomplete, but i noticed the inflexibility and incorporated it.

- i tested with 6500+ users (JSON data simulation) and the autocomplete works flawlessly
- username can be entered without choosing from autocomplete selection

> Note: The autocomplete in the add-on is not a autocomplete like in Jira. Its a static version only in the dialog using an users object which got prevsiously loaded entirely from Jira with a single request.

Will be available soon - next release. Will update here as soon its released.

BTW: There is still a limitation of max *1000* users able to search through. Jira Api is limiting it to max 1000. Not that i think anyone is using Jira with more than this, but just wanted to mention it :)
I can test real live functionality only with about 15+ users here  hehe

**Comment by Blondstar** [comment]
Thanks!
This will make my life much more easier!
Ill be happy to help test!
Let me know when it's available
Many thanks again!


On Mar 23, 2019 11:16 PM, Jens <notifications@github.com> wrote:

Thx for the valued input.
I cant think of a reason, a user would create timereports for users he isnt allowed to find via autocomplete, but i noticed the inflexibility and incorporated it.

  *   i tested with 6500+ users (JSON data simulation) and the autocomplete works flawlessly
  *   username can be entered without choosing from autocomplete selection

Note: The autocomplete in the add-on is not a autocomplete like in Jira. Its a static version only in the dialog using an users object which got prevsiously loaded entirely from Jira with a single request.

Will be available soon - next release. Will update here as soon its released.

BTW: There is still a limitation of max 1000 users able to search through. Jira Api is limiting it to max 1000. Not that i think anyone is using Jira with more than this, but just wanted to mention it :)
I can test real live functionality only with about 15+ users here hehe

**Comment by ljay79** [comment]
I have released it yesterday already, but pending for Google's approval and publishing it. Can happen any minute...

**Comment by ljay79** [comment]
New version 1.2.2 is now approved by Google and published.
You can try the new user selection with autocomplete when create a time report.

Let me know, if there are any issues.
So far, i will close this issue - commenting should still be allowed.

When you like the Add-On, i do appriciate a positive review in the Google Marketplace:
https://chrome.google.com/webstore/detail/project-aid-for-jira/ncijnapilmmnebhbdanhkbbofofcniao

**Comment by Blondstar** [comment]
hi Jens
many many thanks!!!!
it works perfectly! we even migrated some users from a sub company to our jira and I can see the 2 users that are the same and select between them (name is the same but user name not)!
many thanks again!!!!!


________________________________

**Comment by ljay79** [comment]
Perfect, im glad it works.
