### ISSUE TITLE
Affects Version Field Missing

### ISSUE THREAD

**Issue by Tcbrine** [ljay79/jira-tools#187]
** Provide a general summary of the issue in the Title above **

** Provide a more detailed information of the issue **

** Provide Debugging information **
AANBUuXogR+sGGhc2stCWPsAu5EOst0g8zKhMtAHLtUG2aM1HTKpyQiAZosqhr/I6MhPtCHv98D5

### Steps to reproduce
** Provide a set of unambiguous steps to reproduce this bug include code, if relevant **
1. Select menu option "List issues from filter"
2. View System Columns

### Expected result
** Tell us what should happen **
1. Should see either "Affects version" or "Version" (as per field map) as an option.

### Actual result
** Tell us what happens instead **
1. No field corresponding to Affects version field is visible, despite all issues in the filter I am using having this field visible and populated.
<img width="660" alt="Screen Shot 2019-03-26 at 1 48 40 PM" src="https://user-images.githubusercontent.com/13103665/55032386-fe02d800-4fcd-11e9-8e8a-2ae77e6b6fc3.png">

**Comment by ljay79** [comment]
The @Tcbrine for reporting this.
The field apparently just got forgotten.

The new version 1.2.3 has it now implemented and is published to [Google's marketplace](https://chrome.google.com/webstore/detail/project-aid-for-jira/ncijnapilmmnebhbdanhkbbofofcniao) .
As soon Google reviewed and approved the release, it will be automatically updated for all users and then you can use that field.

Feel free to report any further issues here and if you are happy; leave a review at the [Google Marketplace](https://chrome.google.com/webstore/detail/project-aid-for-jira/ncijnapilmmnebhbdanhkbbofofcniao).

Thx
