### ISSUE TITLE
Usability issue with settings

### ISSUE THREAD

**Issue by paul-lemon** [ljay79/jira-tools#190]
Reported by one of the team I work with.
The settings screen suggests the URL for the server would be 
_Jira URL (https://YOURCOMPANY.atlassian.net/)_
we use a private server so the server is a completely different domain and does not have "atlassian.net" in the URL.
However when first setting it up they thought "ourcompanyname.atlassian.net" would be the correct value and they needed my help to configure it.
Since every user must configure the add on and if they fail they can't use it - this seems worth trying to improve e.g.
_Jira URL 
(use your Jira domain name or https://YOURCOMPANY.atlassian.net/ for a cloud Jira instance)_

![Screen Shot 2019-03-28 at 20 14 34](https://user-images.githubusercontent.com/2955356/55187989-93eb5e00-519a-11e9-9d1d-3416885d505d.png)

**Comment by ljay79** [comment]
Understand. Agree it can be improved.
Will think of a clean way.. It must be short. Forms with long explanations are not good for UX.

I have my ex-project partner requested to get a hand on this add-on to make a full redo of all the UX (styling etc.) will put this one here onto the list.

**Comment by ljay79** [comment]
solved with v1.4.0 (commit: [3a55de8](https://github.com/ljay79/jira-tools/commit/3a55de82b09f66d5f5bec568dd71d9158dd7988c))
