### ISSUE TITLE
Unable to connect Jira using Project Aid Addon 

### ISSUE THREAD

**Issue by nsivabalan123** [ljay79/jira-tools#193]
I am getting DNS error. while configuring JIRA details
Exception: DNS error: https://jiradev-bsn.broad<?>Ok

Please help me how to fix this issue.

Thanks in Advance.

**Comment by ljay79** [comment]
Hi.

The Add-on runs online within Google environment and can not access any local/private domains or hosts.
The domain "jiradev-bsn.broad" does not appear to be a public online ressource.

**Comment by nsivabalan123** [comment]
So what are all domains works. I am part of broadcom. Need to connect JIRA in google sheet and extract the data via JQL configured in Google sheet. Please share your thoughts.

**Comment by ljay79** [comment]
your domain, appears to me, as an internal service within your corporate network only. As long as you can not access that Jira instance from outside of the network, it wont be possible to use any such services like my or other add-ons.

If you can, try to make the service accessible remotely via a public domain service.

**Comment by nsivabalan123** [comment]
Our Google is cooperate setup authenticated by OKTA, and worked as intranet service.

**Comment by ljay79** [comment]
It's not the Google service which matters here atm. It's the jira instance.
If jira is not publicly accessible by a public domain, no service such as a
Google add-on will be able to connect to it.

It works like that, an addons runs in the Google public cloud, everytime
you try to use my addon for example it will need to perform api requests
from the Google cloud to the jira instance.

Basically, if you can not access jira from home, your mobile device or
anything else outside your intranet, then this and other addons won't work.

Sry

Jens

nsivabalan123 <notifications@github.com> schrieb am Fr., 5. Apr. 2019,
11:15:

**Comment by ljay79** [comment]
So basically your only option would be, to get some Plugin for Jira which work the other way... Exporting data from within Jira to an external service. Such Add-Ons are available within the Jira Marketplace and usually require your Jira Admin to purchase and install them.
