### ISSUE TITLE
Can't display Estimate story points

### ISSUE THREAD

**Issue by vincentchan** [ljay79/jira-tools#20]
This add-on is so awesome. But for some reasons, I can't get the Estimate story point values. It just shows all ZERO in that column. Do you know why? Thanks.

Vince

**Comment by ljay79** [comment]
Hi @vincentchan ,

thanks for using my add-on. 
Estimate Story point i do not yet support in the coulmns to display.
The existing "Estimate" column is the estimate in time you can maintain in Jira but not to mixup with story points.

PS: Dont forget to write a feedback within Google Add-on Store :)
