### ISSUE TITLE
Error "No filters available!"

### ISSUE THREAD

**Issue by locolab** [ljay79/jira-tools#202]
** Provide a general summary of the issue in the Title above **
I successfully connected to my Jira Cloud account using username and API token but no filters are available. I have 10 board-level filters that should be showing up. "Configure Custom Fields" seems to be working properly, as well as Jira Field map. But when I go to "List issues from filter", I get the error message "No filters available!". The Chrome dev console is showing this message: 

`
There was an error during the transport or processing of this request. Error code = 10, Path = /wardeninit
`

I'm working on Chrome Version 73.0.3683.103 (Official Build) (64-bit) on Mac OSX, although I also tried Safari and it did not work either.

Additionally, I tried using both my personal gmail/gsheet account as well as my GSuite org account, still did not work. 

** Provide Debugging information **
Ok I activated debugging. Here's my temp user key: AANBUuVEebzJu5PTGALEmPbCmbGfvOIj0JATaluOlGhwH59zVKBQOQ6d2KwbbYSN5MWXe1OLs8Ik

**Comment by locolab** [comment]
I had not starred any filters. For some reason I did not equate this to the authors "You must favorite at least one filter". Oops!

**Comment by ljay79** [comment]
Glad you figured it out. I must see in the future if I'm able to have this favorite starring not being required.
