### ISSUE TITLE
Error when trying to create new query from filter [405]

### ISSUE THREAD

**Issue by sshouse** [ljay79/jira-tools#203]
I have several favorited filters, and this was working until recently, now I get the following error message:
No filters available!Failed to retrieve jira filters with status [405]!\nMethod Not Allowed

**Comment by ljay79** [comment]
Hi.
Sorry for the inconvenience.
Are you using Jira Server or Jira Cloud?

**Comment by ljay79** [comment]
Can you please check, if the issue still occurs.

**Comment by ljay79** [comment]
[abandoned]
