### ISSUE TITLE
No issues with worklogs available for user ...

### ISSUE THREAD

**Issue by mirkea** [ljay79/jira-tools#204]
Hi. I'm using JIRA  cloud and our instance is configured to authenticate with Google. 
I installed the extension and configured it using email and API token. The extension seems to work for the most part (such as list JIRA issues from filter) except the part I need the most: time reports.

What happens is that I open "create time report", select a user and an interval and when I click Create report I get this error
>Apparently there are no issues with worklogs available for Mircea in the requested time period.

The weird thing is that [the call gets cancelled apparently for some reason.](https://i.imgur.com/t1Bsh9P.png) (I don't have an adbocker enabled or anything like that; I tried with Firefox and same issue)

I made the calls with multiple users and different intervals where there are definitely logged hours.

Temp user key: 
```
AANBUuVme6iol8HXTsvs+xkrm0CwOuuWUcjhKtmk/Szx7k8RQroAtH0MRfplwUs56P+HQG6C+6EU
```

**Comment by ljay79** [comment]
Hi @mirkea 
Thanks for taking the effort reporting this issue.

I have checked the logs associated with your provided user key (hx for that).

I can see the query for worklogs for the user _mircea_. The Jira API indeed returned an empty result, telling no records found.
Here is the underlzing JQL query which the add-on does execute to fetch worklogs:
`worklogDate>="2019-04-01" AND worklogDate<="2019-04-23" AND worklogAuthor="mircea" ORDER BY created DESC`

You can use the same JQL query and run it in your Jira webinterface at advanced search.
Please check, if it will return you any logs there.

replace the jira domain with yours:
`https://[jira-instance].atlassian.net/issues/?jql=worklogDate%3E%3D%222019-04-01%22%20AND%20worklogDate%3C%3D%222019-04-23%22%20AND%20worklogAuthor%3D%22mircea%22%20ORDER%20BY%20created%20DESC`

**Comment by mirkea** [comment]
Hi Jens
thanks for the quick (and helpful) response. It seems like that is indeed the query result and the reason for it seems to be that we're using Tempo (timesheets) which acts as a middleman.  If I change the JQL query to
```
worklogDate>="2019-04-01" AND worklogDate<="2019-04-23" AND worklogAuthor="addon_is.origo.jira.tempo-plugin"
```
then the worklogs shows up, but obviously it shows up for all the users. It seems like the problem is not with Jira Aid, so this is not a bug after all

**Comment by ljay79** [comment]
Glad i could help.
I had used the Tempo plugin in the past, but dont have it anymore.
But i remember you could do quite pretty reports with it inside Jira already, no need to go the way around with google sheet.

On the other hand, if you prefer to have it in sheets... maybe you can investigate a bit how Tempo does store this data and maybe it does make it accessible via Jira JQL in a different way but still allowing to select by user. Maybe the field isnt `worklog...` maybe something else.

If you figure something JQL based out, i can certainly have a look on it. and if/how i could implement Tempo support into my Add-on.

Feel free to comment here on that issue.
