### ISSUE TITLE
Status colouring makes text difficult to read

### ISSUE THREAD

**Issue by Tcbrine** [ljay79/jira-tools#206]
More of an enhancement than a bug, but I would like to be able to switch off the colouring of text corresponding to Jira statuses as my users find the bright yellow and green quite hard to read.

**Comment by ljay79** [comment]
Yes @Tcbrine i have the same thoughts. Will remove the coloring soon.
I guess its easier for users to add conditional coloring afterwards than removing them.

**Comment by ljay79** [comment]
Coloring of the Status and Resolution fields has been removed in latest release.
