### ISSUE TITLE
Sort Order of Columns

### ISSUE THREAD

**Issue by Frankyg30** [ljay79/jira-tools#210]
is it possible to specify the column order when pulling the data from Jira?

**Comment by ljay79** [comment]
Hi @Frankyg30 this is currently not possible except for the custom functions like _JST_search()_ .

The current order of columns for Issue tables inserted via menu "Create Issue list from filter" would be,
in order:
key: 'Key',
summary: 'Summary',
project: 'Project',
issuetype: 'Issue Type',
priority: 'Priority',
status: 'Status',
labels: 'Labels',
components: 'Components',
description: 'Description',
assignee: 'Assignee',
creator: 'Creator',
reporter: 'Reporter',
environment: 'Environment',
fixVersions: 'Fix Version',
versions: 'Affects Version/s',
duedate: 'Due',
resolutiondate: 'Resolved',
created: 'Created',
updated: 'Updated',
resolution: 'Resolution',
timespent: 'Time spent',
timeestimate: 'Remaining Estimate', // remaining
timeoriginalestimate: 'Original estimate',
aggregatetimeoriginalestimate: 'Σ Original Estimate',
aggregatetimespent: 'Σ Time Spent',
aggregatetimeestimate: 'Σ Remaining Estimate',
aggregateprogress: 'Σ Progress',
progress: 'Progress',
lastViewed: 'Last Viewed',
votes: 'Votes',
watches: 'Watchers',
workratio: 'Work Ratio'
...
any selected custom field in order it has been enabled/activated in the "Create Issue List from Filter" screen.

**Comment by ljay79** [comment]
abandoned
