### ISSUE TITLE
List Issues from Filter inserting duplicate EpicLink columns

### ISSUE THREAD

**Issue by skorecki** [ljay79/jira-tools#213]
** Provide a general summary of the issue in the Title above **
The Epic field is being duplicated 6-7 times on my sheet for each time I load/refresh the table.

** Provide a more detailed information of the issue **
I have an existing sheet that has been using Project Aid for Jira for at least 3 weeks.  I refresh the table every few days.  When I did so today it was taking an extremely long time.  At first, I saw that there were numerous duplicate columns titled "Epic" and every value was in a "Loading" state.  I eventually deleted the table and re-inserted a new table.  This time the Epic column was repeated 7 times.  The values eventually loaded but took approximately 5 minutes for 274 rows.  This is much longer than usual and seems to be because of the additional time needed to load the Epic links.  The first Epic column had all values of "undefined" and the other 6 Epic had the correct hotlinks to the Epic.  However, there should only have been one column for Epic.
After setting the debug value, I refreshed the table.  This inserted 6 more duplicate Epic columns -- resulting in a total of 13.

** Provide Debugging information **
For further investigation, please activate Debugging in "About" dialog, provide us with your "Temp. User Key" and then perform at least one another try. This way it will log the error and debug information to project owners StackDriver logging account where we can analyze it better.
>Note: User credentials are not transmitted in any log data.
Temp.User Key:  AANBUuUpTbBWKPCJpe1BmioisZPoaFzKSkBoCTVHA1kqBCXGi5WMwkLSKyhZoQbU/niR4GCP7h7h

### Steps to reproduce
** Provide a set of unambiguous steps to reproduce this bug include code, if relevant **
1.  Insert List of Issues from Filter 
2.  Select the Epic field to be included in the table.
3.  Let the table load
4.  Refresh Issue table

### Expected result
** Tell us what should happen **
1.  Selected fields in filter populate the sheet with the no duplicate columns upon insert.
2.  Upon refresh, the table is updated with the same number of columns (no duplicates added)

### Actual result
** Tell us what happens instead **
1.  Instead of one Epic column in the initial load, there are 7.  All values in the first "Epic" column have a value of "undefined".  The values in the 6 other columns take a long time to load, but eventually fill in with the correct hotlink to the Jira Epic issue.
2.  After refreshing the issue table, there are 13 Epic columns.  Once again, the first one is filled with all "undefined" values.  The next 12 are filled with the correct hotlink value, but take a long time to load.
![1 - List Jira issues from filter dialog - Google Sheets](https://user-images.githubusercontent.com/1108333/58049047-e8b3b100-7b19-11e9-87a8-e9ffd1169fde.png)
![2 - Epic columns loading after 5 minutes - Google Sheets](https://user-images.githubusercontent.com/1108333/58049055-eea99200-7b19-11e9-993d-5fccd507dcfa.png)
![3 - Epic Columns loading after refresh - Google Sheets](https://user-images.githubusercontent.com/1108333/58049063-f36e4600-7b19-11e9-96dd-23f989a92d6b.png)

**Comment by ljay79** [comment]
Thanks for this very detailed bug report.
I certainly will have a look at it.

**Comment by ljay79** [comment]
I tested myself and i can actually reproduce it when i have the "Epic" field selected as well.
Without the Epic field i can not reproduce it. Will work on a fix right away.

**Comment by ljay79** [comment]
I have release version 1.3.6 with a fix for this issue. Waiting now for google to publish the update.
I'll keep you noticed.

**Comment by ljay79** [comment]
Version 1.3.6 which includes the fix is now available and will automatically be updated.
Please verify the issue has been solved.

**Comment by skorecki** [comment]
Fantastic!  Thanks for the quick turn around!  Everything seems to be working now!

**Comment by skorecki** [comment]
Closing this issue
