### ISSUE TITLE
Cannot Refresh Issuetable

### ISSUE THREAD

**Issue by kb1638** [ljay79/jira-tools#228]
When you click refresh Issuetable, no 'refresh' button appears in righthand popout column 

Steps to reproduce

1. Add-ons > Project Aid for Jira > Refresh Issuetable

Expected result

Refresh button should be available to allow Issuetable to pull updated data from Jira

Actual result

Message reads: "You do not have any Jira "IssueTable" in your current sheet(s).
Menu: Add-ons > Project Aid for Jira > List issues from filter"

**Comment by ljay79** [comment]
Hi there.
Did you inserted an IssueTable in the current sheet with menu "Create new IssueTable" or "Create IssueTable from filter"?

The sidebar "Refresh IssueTable" will show you jira issuetables to refresh, only if you have actual IssueTables in the current sheet.

Sample with no IssueTable in sheet:
![jst-228-issuetable_empty](https://user-images.githubusercontent.com/12184976/59754659-d0ed5b00-9286-11e9-9078-ce75f2a6fd26.jpg)

Sample with 1 IssueTable in sheet:
![jst-228-issuetable_exists](https://user-images.githubusercontent.com/12184976/59754678-db0f5980-9286-11e9-826f-31041a98db5c.jpg)

**Comment by kb1638** [comment]
Hi thanks for the help!

There is an issuetable but weirdly, some tabs with issuetables are missing the 'refresh' button while others have the 'refresh' button. However, even the ones with the 'refresh' button will not refresh when the button is clicked. It continues to say "Updated: >8d23m" even when clicked. 

![j1](https://user-images.githubusercontent.com/51971625/59771585-08084000-9278-11e9-9ef2-8eb67670140d.PNG)

Any ideas of why some buttons have disappeared while others remain but cannot update? Everything was working fine prior. Assumed it was a bug in the gdoc to jira connection but if no one else is having this problem then maybe not.

**Comment by ljay79** [comment]
This feature "Refresh" is at this stage independent of Jira connections.
It relies on the process of inserting a new table, stores the info and uses it to allow the box display with "Refresh" on the right sidebar.

Im not really sure, why some would work some not, and why some would not refresh anything.

a)
Try (just for test) with a new empty sheet and insert one or more IssueTables, check behavior of the Refresh feature.

b)
For further debugging of your issue i would need more data.
Please activate Debugging in "About" dialog, provide me with your "Temp. User Key" and then perform at least one another try. This way it will log the error and debug information to project owners StackDriver logging account where we can analyze it better.
>Note: User credentials are not transmitted in any log data.

When debugging active:
- new empty sheet
- Insert IssueTable from filter
- open sidebar "Refresh IssueTable"
- (if visible) hit "Refresh" Button for newly created IssueTable

If you do multiple tests, ie with the other problematic tables, please leave some seconds/time between the tests and take note of the date+time you performed the tests individually.
This way i can better separate all the logs between all your test cases.

**Comment by ljay79** [comment]
abandoned
