### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by RichardKnoos** [ljay79/jira-tools#229]
When I try to install the plugin via: https://gsuite.google.com/marketplace/app/jira_sheet_tools/248954272770

I get the following error after authenticating with my google account:

"Sign in with Google temporarily disabled for this app
This app has not yet been verified by Google in order to use Google Sign in."

![image](https://user-images.githubusercontent.com/25826720/62136947-67308a00-b2e5-11e9-9239-1bbdf8e1a39e.png)

**Comment by ljay79** [comment]
Hi.

This is an temporary issue with google. I have filed a request already, but it's hard to get an actual person there.

Try installing the on directly from with google sheets, then in add-ons > get add-on.

**Comment by ljay79** [comment]
abandoned
