### ISSUE TITLE
"Project Aid for JIRA" add-on doesn't work today

### ISSUE THREAD

**Issue by ykostiv** [ljay79/jira-tools#231]
** Provide a general summary of the issue in the Title above **

** Provide a more detailed information of the issue **
Error
Error: There was a problem fetching your settings from the Google Service. Please try again later. (line 21).

** Provide Debugging information **
For further investigation, please activate Debugging in "About" dialog, provide us with your "Temp. User Key" and then perform at least one another try. This way it will log the error and debug information to project owners StackDriver logging account where we can analyze it better.
>Note: User credentials are not transmitted in any log data.

### Steps to reproduce
** Provide a set of unambiguous steps to reproduce this bug include code, if relevant **
1.
2.
3.

### Expected result
** Tell us what should happen **
1.

### Actual result
** Tell us what happens instead **
1. [Screenshot, logs]

**Comment by ljay79** [comment]
Hi @ykostiv,

For further investigation, please activate Debugging in "About" dialog, provide me with your "Temp. User Key" and then perform at least one another try. This way it will log the error and debug information to project owners StackDriver logging account where we can analyze it better.

**Comment by ykostiv** [comment]
Temp User Key: AANBUuVqG7tt5UQgAx2yECBl0R+9dHppgGLRH3yIUXsKYU1URpVHFfz/gf1WIADyLavWGieTUzPP

**Comment by ykostiv** [comment]
visually, it loads data for quite a long time, than falls down to an error. It looks like timeout error, being honest - maybe JIRA API has changed?

**Comment by ykostiv** [comment]
I'm using just one function JST_getTotalForSearchResult, but many times )

**Comment by ykostiv** [comment]
ok it works now, thank you!

**Comment by ljay79** [comment]
I'll will have to check. In past this us usually happen when a user reaches the daily google quota limits.
Can you roughly estimate how many function calls are in your sheet and how often all of them are updated over a time window of 24 hours?

**Comment by ljay79** [comment]
Google does sadly not indicate in any way if a limit is reached and therefore its hard/impossible to differ between a limit issue or any other issue related to that call.

**Comment by ljay79** [comment]
I'm glad it works now, however I did nothing yet ;)  another indicator it simply hit the 24h quota limit. I have a look at the logs later...

**Comment by ljay79** [comment]
@ykostiv  You are from devfactory.com as well. Nice, Im sure i had at least 1 or 2 other guys from your team here already in past. Seems you guys like my add-on. I appriciate to see that :)
Thx

**Comment by ljay79** [comment]
Issue is duplicated to #196 
(Issue resolved by itself.)

Suspected google dailys quota limits.

**Comment by ykostiv** [comment]
Yes, we do like your addon, but Google doesn't ) I don't know what it is, nobody is looking at this spreadsheet at least since a week, it's just me and not much. Same problem again: can't fetch Google data. How many requests? there are 3 worksheets, each is generating roughly 300-400 requests, but I'm not enforcing when I can see some numbers.

**Comment by ljay79** [comment]
Hmmm...   who is owning the spreadsheet, you?
Can you please verify/repost your temp user key. With the provided key above the last single and only log entry i found is from the 5th at 20:40 CEST.

And error logs like yours usually get logged by google even without debugging active.

**Comment by ykostiv** [comment]
yes I am the owner. But under different email: yuriy.kostiv@trilogy.com
but I have installed add-on under yuriy.kostiv@devfactory.com as it totally stopped working under trilogy account, so I had to de-install it

**Comment by ykostiv** [comment]
By the way, under Trilogy account, when I try to go to Settings, I'm getting exactly the same error.
<img width="1113" alt="Screen Shot 2019-08-07 at 20 13 25" src="https://user-images.githubusercontent.com/52833954/62643094-dc3c3900-b94f-11e9-8901-2702a064cd44.png">

**Comment by ykostiv** [comment]
Oh wow, very interesting, this is what I've just got when I tried to go to "About" dialogue under Trilogy account - German message more clearly and proves your theory about quota, but it doesn't fit the reality - there was nobody looking at this spreadsheet except me since July 31 and I haven't added that much. Allright, let me try to split this spreadsheet in several then...
<img width="862" alt="Screen Shot 2019-08-07 at 20 15 02" src="https://user-images.githubusercontent.com/52833954/62643327-65ec0680-b950-11e9-96f4-5b29cd294ba8.png">

**Comment by ykostiv** [comment]
Just made a new copy of that spreadsheet and the numbers started to fetch in. Google must have got tired of the old one )

**Comment by ljay79** [comment]
I must admit I'm not fully aware if how the quota applies. Maybe its per api call independent of the addon. Btw: every call / action in the addon requires multiple calls to the troubling service. I'm still trying to figure a good approach for cache, so the limit isn't so easily reached....

**Comment by ykostiv** [comment]
I can't find anywhere any description what is the "issue table"? Is that a cache?

**Comment by ykostiv** [comment]
ok I guess the best would be to dump yourself an issuetable, if there are more requests to the same dataset?

**Comment by ykostiv** [comment]
so far I have split my spreadsheets in 3, seem to be working so far

**Comment by ljay79** [comment]
Can you maybe describe in more detail how you interact and use the addon   thus way I can maybe find a workaround are even advise on a less quota impacting approach.

**Comment by ljay79** [comment]
Btw: are you / your account german or why did you got a german error message?

**Comment by ljay79** [comment]
Is the following user key maybe one of yours?
Key: _AANBUuU3lh7pG7v9Qawjm9H7vafu2myoswGtoApFfFEBGtBWBC9PiSEkE5o+UsLkxTOUQpjUiOEZ_

**Comment by ykostiv** [comment]
No idea. No, it's not German. English.

**Comment by ykostiv** [comment]
AANBUuVqG7tt5UQgAx2yECBl0R+9dHppgGLRH3yIUXsKYU1URpVHFfz/gf1WIADyLavWGieTUzPP
this is mine

It's the same with all 4 spreadsheets: 3 new ones I have created to fetch data and the old one, importing that data into the report

**Comment by ljay79** [comment]
PS: Its the owner of the spreadsheet who is used for custom functions executions. So make sure, to provide me the owners users key pls.

**Comment by ykostiv** [comment]
I am the owner of all spreadsheets I have mentioned

**Comment by ljay79** [comment]
Yep now. I can see. Thats the same key you provided 2 days ago, but at that time there was like nothing (good nor bad) in the logs. Today i can see quite some logs for this key.

**Comment by ykostiv** [comment]
I believe there is something wrong with that spreadsheet. I have removed the add-on from it, it's just collecting the data from the other spreadsheets now. Question: do I have to keep those spreadsheets open so the data up-to-date or is it doing something in the background?

**Comment by ljay79** [comment]
Wow, you really seem to be an heavy user... we should maybe really talk about some improvements on the usage or workarounds...
Just in 1 minute, you (your sheet) did around 300 API calls to Jira. Every single call would internally result in multiple calls to fetch properties from the add on etc. which also counts towards the quota limit you had expirienced. So we talking about 300x 5-10 calls per single minute...

When you close the spreadsheet, there isnt anything to update your data - at least not from my addons logic.

**Comment by ljay79** [comment]
I notice quite some JQL erros for this user as well (cant tell which sheet).
Im have implemented some logic for limiting such user errors to prevent endless loops of calling apis and services when the sheet has to many errors. Its in "soft" mode yet - meaning only logs potential suspension but does not enforce them.

You do trigger the 5min suspension due to user (JQL) errors already quite often :)

Once, i active that feature, you would notice   hehe

**Comment by ykostiv** [comment]
very good stats, we need to have a transitional DB to access for reporting purposes - central JIRA is going to die under this load. I'm afraid I have to think of some helper dumps to work with, I have really built pretty complex logic, based on JIRA queries

**Comment by ljay79** [comment]
Sure, again: if you like to share a deeper insight of your heavy use case, im more than happy to look into it and try figure a way of improving the add-on making it not onyl easier for you and other but also less "quota error" prone.


Just for reference:
https://developers.google.com/apps-script/guides/services/quotas

The one specific you hit already is:
Properties read/write | 50,000 / day | 100,000 / day | 500,000 / day | 500,000 / day

**Comment by ljay79** [comment]
Your key "AANBUuVqG7tt5UQgAx2yECBl0R+9dHppgGLRH3yIUXsKYU1URpVHFfz/gf1WIADyLavWGieTUzPP" is not causing any logs since about 30 mins, but therefor the user key "AANBUuVqG7tt5UQgAx2yECBl0R+9dHppgGLRH3yIUXsKYU1URpVHFfz/gf1WIADyLavWGieTUzPP" which appears to use the same sheet or similar. For sure is from devfactory too.

**Comment by ykostiv** [comment]
I have closed all sheets generating requests for now ) Thinking how to improve it

**Comment by ljay79** [comment]
For me it not a problem per se. The quota affects the user only :)

Let me know, in case you like to discuss improvements on your and my (addon) end.

When you closed the sheets, then someone else of your team uses same or similar sheets :) BC the logs from the other key is not stopping ... no problem to me at all, just wanna mention it.

**Comment by ykostiv** [comment]
it is designed to be open and used by the other people, but I am looking at view stats, I'm the only one since 7 last days

**Comment by ljay79** [comment]
abandoned
