### ISSUE TITLE
time report options

### ISSUE THREAD

**Issue by Blondstar** [ljay79/jira-tools#232]
Hello, 
I would like to have a different view of the time reports, where the report is by the date and not by the task
the reasons for this are: 
when I have a long range of dates, its very hard to look at the info when the date  is a row
I would like to have a table where I can add multiple users and  and with the display its not possible
maybe there can be an option to select how the view is? for example display by date or display by issue? 
(I tired to manipulate sheets to obtain the below view but I didnt manage to do it... if there is a way I can achieve the below view I would be very happy to know) 

below is an example of how I would like the report to look
![image](https://user-images.githubusercontent.com/48771668/62554372-48943b00-b871-11e9-8c4a-8cfe74e07e41.png)

Many Thanks!

**Comment by ljay79** [comment]
Hi @Blondstar thanks for using my add-on and thanks for submitting a feature request.
Your above sample shows decimal numbers for the column "Date". So to clearify, what is it exactly you like to get listed in such report?

If you could use actual (default) Jira Key names in the columns of your sample its better to refer to standardized fields.

**Comment by Blondstar** [comment]
Hi @ljay79 
sorry for not being clear, the 'decimal' number under date are the date of the month August. 
I update the image, using the date format you use in the report
the key name is actually the key I get from your time report. Im not sure what default key names are... 
but the idea is to get the same data from the original report, just with a different view... 



![image](https://user-images.githubusercontent.com/48771668/62570258-c6ffd580-b88f-11e9-9d9f-0069dd0d7de1.png)

**Comment by ljay79** [comment]
Ok thx, i will have a look at this on how fast i could implement such...  pls be patient with me, just have a lot around me these day...

**Comment by Blondstar** [comment]
Thanks!
please let me know if you have a timeframe idea... I wanted to base my reports on it but if you think it will take a very long time... I will try to find a workaround until you get to it

many thanks again!!!!!!

**Comment by ljay79** [comment]
I think you will be happy :)

Below is a screenshot of my working dev environment - 2 actual generated tabeles.
Will need a bit more tweaking, testing and finetuning, but i guess you can expect it sooner then i thought.

![jst-timesheet-layouts](https://user-images.githubusercontent.com/12184976/62634157-b30eaf00-b935-11e9-8a15-5d88912594f9.jpg)

**Comment by Blondstar** [comment]
perfect! you are my hero!

cant wait!

**Comment by ljay79** [comment]
Release version 1.4.2 including the update with now 2 timesheet layouts to choose from has been published and is rolling out through google services.

Please let me know, once updated, what you think.

**Comment by Blondstar** [comment]
woho!
testing it in 5!
many thanks!

**Comment by Blondstar** [comment]
its great! thanks! it would be nice if the date column is sorted, but its not a problem to sort it with google sheets :)

Thanks!!!

**Comment by ljay79** [comment]
The Layout 2 "Dates -> Issues" is actually sorted. At least it should and works for me..

**Comment by Blondstar** [comment]
I get this

![image](https://user-images.githubusercontent.com/48771668/62718103-7f9b5580-ba05-11e9-8869-2ac450937780.png)

**Comment by ljay79** [comment]
Hmm ok. Then this is a bug. Will check it soon

**Comment by Blondstar** [comment]
Thanks! works perfect! already used it today to create my weekly report!

**Comment by ljay79** [comment]
Great. Im glad it helps you.

Feel free to rate/review my add-on in the G-Suite marketplace:
https://gsuite.google.com/marketplace/app/project_aid_for_jira/248954272770

Thx.
