### ISSUE TITLE
Show Estimate as raw time (hours, minutes, days)

### ISSUE THREAD

**Issue by nerocom** [ljay79/jira-tools#239]
I'm trying to figure out if this is a "feature" request or a mistake on my side.

Using a function such as:
`_=JST_search("sprint = 157 ORDER BY type DESC", "key,issuetype,summary,timeoriginalestimate", 50)_`

The timeoriginalestimate shows as like 1d or 3h which is not usable in excel. 

Possible to make it so it shows a consistent format (such as hours) that can be used in excel for calculations?

**Comment by ljay79** [comment]
Hi, you can change the format of duration fields in the settins:

![duration](https://user-images.githubusercontent.com/12184976/63795533-6ac72900-c904-11e9-9e34-be45d048621a.jpg)
