### ISSUE TITLE
Project Aid For JIRA - Error 401 Unauthorized

### ISSUE THREAD

**Issue by christmurphy** [ljay79/jira-tools#240]
Steps to reproduce
1. Open Google Sheets > Add-Ons > Project Aid for JIRA > Settings
2. Used proper JIRA link, username and password. Receiving a 401 Unauthorized error. 

I have checked with our JIRA admins and they are not seeing any failed login attempts.

**Comment by ljay79** [comment]
Please see the Readme, section [Atlassian API Token](https://github.com/ljay79/jira-tools#b-atlassian-api-token)

**Comment by christmurphy** [comment]
@ljay79 Thanks for the help! This seems to have fixed the issue.

**Comment by ljay79** [comment]
Im glad it helped. Have fun
