### ISSUE TITLE
Feature: Support to create issues in Bulk

### ISSUE THREAD

**Issue by rohinrohin** [ljay79/jira-tools#241]
Hi, 

Is there a feature in the pipeline to allow creating issues in bulk?
I am in need of this feature and am happy to work on it if it makes sense for you. 

I would need features like auto-create into the current sprint.
 
Thank you :)

**Comment by ljay79** [comment]
Hi @rohinrohin at this moment there is nothing really in the pipeline.
This add-on is more for pulling daten and reports rather than an external editor kind of app.
