### ISSUE TITLE
Can't reconenct to Jira -unauthorized error

### ISSUE THREAD

**Issue by erolveraMx44** [ljay79/jira-tools#242]
** Provide a general summary of the issue in the Title above **
From my google account, I can't reconnect to JIRA repository to get issues table.

** Provide a more detailed information of the issue **
I can't reconnect using my credentials in a specific laptop. I tried from a different equipment and I was able from a different PC. But in my daily lap, I'm blocked. I uninstall and reinstall the add-on and it didn't works. 

** Provide Debugging information **
For further investigation, please activate Debugging in "About" dialog, provide us with your "Temp. User Key" and then perform at least one another try. This way it will log the error and debug information to project owners StackDriver logging account where we can analyze it better.
>Note: User credentials are not transmitted in any log data.
User-Key == AANBUuVj397zHXL6X4RS7U5SrEEV1CubwrnXYo9bLuPr3YidOHi/eM7uIL/58RLDWoVUqL3GxWbl
### Steps to reproduce
** Provide a set of unambiguous steps to reproduce this bug include code, if relevant **
1. Settings jira server link
2. add user and password
3. Save settings
4. Click Create issuetable from filters and get error message: "No filters available!Failed to retrieve jira filters with status [401]!\nUnauthorized" 

### Expected result
![2019-10-21_17h14_29](https://user-images.githubusercontent.com/56849225/67247528-4cbf0600-f427-11e9-8eea-373394ad7a36.png)
** Tell us what should happen **
1. A list of filters from JIRA

### Actual result
** Tell us what happens instead **
1. Error message "No filters available!Failed to retrieve jira filters with status [401]!\nUnauthorized"

**Comment by ljay79** [comment]
Hi @erolveraMx44  please check the README and try to proposed solution there in Section "Known Issues".
https://github.com/ljay79/jira-tools#known-issues

Let me know, if this helped.

**Comment by ljay79** [comment]
orphaned
