### ISSUE TITLE
example for "update formula" feature

### ISSUE THREAD

**Issue by albasili** [ljay79/jira-tools#244]
Hi there,

I didn't quite understand how this feature works. Can you provide an example in the README? I'd be glad to open a pull request if you can explain me how it works.

Appreciate your support.
Al

**Comment by ljay79** [comment]
Hi @albasili 
do you mean this function here?
“Add-ons" > “Project Aid for Jira” > "Update formulas in active sheet"

**Comment by albasili** [comment]
@ljay79 exactly

**Comment by albasili** [comment]
I've found the examples in the "Custom Functions" section. No extra explanation is needed
