### ISSUE TITLE
enhancement - reference cells from within JQL query. 

### ISSUE THREAD

**Issue by jkirschling** [ljay79/jira-tools#245]
I have a query like this - 
=JST_getTotalForSearchResult("Sprint = 'Sprint 20.1'")

I want instead to reference the sprint name from another cell like
=JST_getTotalForSearchResult("Sprint = F1")

Is there a way to escape or reference cells from within the query function? 

If not, it would be a very useful feature enhancement!

**Comment by ljay79** [comment]
Hi @jkirschling , you can actually do this with the google sheet function `CONCAT`.
Sample:
`=JST_getTotalForSearchResult(CONCAT("Status = "; B1))`

**Comment by ljay79** [comment]
@jkirschling were you able to check my response and test it?

**Comment by jkirschling** [comment]
Thanks for responding - I haven't, since I no longer work there :) - I'll pass this tip on to my friend who I was trying to help before I left and see if I can get a response.
