### ISSUE TITLE
Unable to generate time reports

### ISSUE THREAD

**Issue by Thapovan-tech** [ljay79/jira-tools#246]
This JIRA bug: https://jira.atlassian.com/browse/JRACLOUD-73879 lead to an immediate inability to generate time reports, as all users showed up as 'Undefined'. The bug has been fixed for 3 days (and the dashboard reflects it) but the addon still has the same issue.

Temp User Key: 
APZqPay7qBXL8BOg0LMIYiviWN2Pq8zjcu4wgVIf+T6RAzepmyw6bGbgH8CYdrcSjrhcsGS+cZHN

### Steps to reproduce
1. Select 'Create Time Report' from the menu
2. Type into the box and select any user that appears. 

### Expected result
1. The user's email address should appear in full next to their name and you should be able to click on the Create Report button.

### Actual result
The user's name is correct but the email address appears as 'undefined'. The 'Create Report' button is greyed out.
![2](https://user-images.githubusercontent.com/61448969/76051397-9e100200-5f90-11ea-8982-c3c6ba257fbd.PNG)
![1](https://user-images.githubusercontent.com/61448969/76051398-9f412f00-5f90-11ea-8d24-966af785f360.PNG)

I am unclear if the bug has truly been fixed and the implementation requires a change on the part of the addon or if they just haven't fixed it properly.

**Comment by ljay79** [comment]
Thx @Thapovan-tech i will investigate this asap.

**Comment by Thapovan-tech** [comment]
Update: A developer has responded to the ticket and said that the bug is not completely fixed: https://jira.atlassian.com/browse/JRACLOUD-73879?focusedCommentId=2369941&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2369941

**Comment by ljay79** [comment]
Thank you for the update, i have started watching it issue there and will check frequently for any updates.

**Comment by ljay79** [comment]
Should be fixed now with released version 1.4.3

**Comment by Blondstar** [comment]
@ljay79 for me it worked before 1.4.3....
today, with 1.4.3 it stopped working... (If I remove the email, and leave the user, the report is generated, but with no values of the worklog
