### ISSUE TITLE
Options are not showing up in the addon

### ISSUE THREAD

**Issue by rake23** [ljay79/jira-tools#251]
Hi,

Thanks for this addon. It help a lot. From this afternoon, we are unable to use this addon. None of the option is showing up except Help. Our jira version is v7.12.1. Please find the screenshot below.

![Addon stopped working](https://user-images.githubusercontent.com/28426859/79766550-bf149280-8345-11ea-8e04-b090762b6196.png)

Thanks

**Comment by ljay79** [comment]
Hi.
I actually had the same issue after my new release. I wasn't able to figure out the actual cause. Can only imagine that is has something to do, as Google changed the entire release process with newer tools and there might be some internal changes.

I was able to solve it by completely uninstall the app and then reinstall fresh from the store.

Let me know if this helped.

**Comment by ljay79** [comment]
Hi @rake23 ,

are you still experiencing this issue? I just want to check in, however i sadly have no new clue for the cause of this.

**Comment by rake23** [comment]
Sorry, forgot to update you back. This issue solved by reinstalling the
app. Thanks for the great support.

**Comment by ljay79** [comment]
Ok, so I guess this was some strange and odd exceptional glitch.
