### ISSUE TITLE
List of filters from JIRA not loading

### ISSUE THREAD

**Issue by vindhya-ashwath** [ljay79/jira-tools#253]
When I click "Create IssueTable from filter" the pop-up opens but the list of filters don't load. The console has the following error.

_Uncaught  at jiraCommon:167 (Project Aid for Jira:77) b87812ce-8027-47e4-9cd0-ef98f9c5dcfe
 at jiraCommon:178 (Project Aid for Jira:77) b87812ce-8027-47e4-9cd0-ef98f9c5dcfe
 at jiraApi:292 (Project Aid for Jira:77) 66e1ffbf-99f0-4651-93b1-929a5146f080
 at getMyFilters (jiraCommon:206) (Project Aid for Jira:77) b87812ce-8027-47e4-9cd0-ef98f9c5dcfe_

For further investigation, please activate Debugging in "About" dialog, provide us with your "Temp. User Key" and then perform at least one another try. This way it will log the error and debug information to project owners StackDriver logging account where we can analyze it better. **Done**

### Steps to reproduce
1. Click on "Create IssueTable from filter"
2. Pop-up opens
3. Continues to say "loading" indefinitely but nothing loads

### Expected result
1. List of JIRA filters should be displayed

### Actual result
1. [Screenshot, logs]
<img width="1419" alt="Screen Shot 2020-05-12 at 12 41 39 PM" src="https://user-images.githubusercontent.com/14722523/81650170-1989a600-944f-11ea-8989-fc35823d1cfe.png">

**Comment by vindhya-ashwath** [comment]
Seems to be due to the number of filters I had.

**Comment by ljay79** [comment]
@vindhya-ashwath sry for my late reply.
Could you elaborate on how you were able to solve the issue.
