### ISSUE TITLE
"Create IssueTable from Filter" leads to infinite "loading filters..." message

### ISSUE THREAD

**Issue by titusfvr** [ljay79/jira-tools#254]
** Provide a general summary of the issue in the Title above **
When trying to create a new table, the pop-up window does not load up the filters from Jira.

** Provide a more detailed information of the issue **
Thank you very much for your work on the addon. It used to work for me a few months ago, then I kind of abandoned the sideproject that involved me using it. Came back to it today, and sadly when I try to create a table from filters, it will not load up the filters. Tried leaving it for about 30 minutes, but to no avail sadly.

** Provide Debugging information **
ALEt7zRAW44G7kvTxTElZ63Vg7IPIUgNGz9vdjXxcGyGmgUDvKjDpVdGSNTtn3K4dBhL2FVnh58r

### Steps to reproduce
** Provide a set of unambiguous steps to reproduce this bug include code, if relevant **
1. Attempt to create issue table from filters
2. Observe issue

### Expected result
** Tell us what should happen **
1. See a list of all the available filters

### Actual result
** Tell us what happens instead **
1. Screenshot
![image](https://user-images.githubusercontent.com/66027347/83048458-843b0400-a041-11ea-8ca5-46e10bab794a.png)

**Comment by ljay79** [comment]
Hi @titusfvr 
it appears you have quite a lot filters, is that true?

Did you try uninstall and back reinstall the add-on?
I will see, what else i can find in the logs...

**Comment by wyojoe** [comment]
I'm expecting the same issue.

When I go to Create IssueTable from Filter I get the infinite "loading filters..." message!

I've removed the extension, re-added it, connected to JIRA with a new token.

[image](https://user-images.githubusercontent.com/33264292/85317418-96ab3080-b47b-11ea-9c92-bd6f6846fa87.png)

**Comment by ljay79** [comment]
@wyojoe 

For further investigation, please activate Debugging in "About" dialog, provide us with your "Temp. User Key" and then perform at least one another try. This way it will log the error and debug information to project owners StackDriver logging account where we can analyze it better.
>Note: User credentials are not transmitted in any log data.

**Comment by titusfvr** [comment]
> Can you let me know what Jira software/type/version you are using.
@ljay79 sorry for my delay in responding - very busy times. We use Jira Cloud so I assume it should be the latest version?

**Comment by wyojoe** [comment]
Hello and thank you for your reply. I'm using JIRA Cloud so I don't think
there is a type or version.


Here is the access code.

ALEt7zQa8BP7fqCtgX4yX9DD1pyBIRI9WTDqfl0SuJFcRi3vZBWZ0bTP3BUCDCCTqbc2VHafQj8Q




Joe Taberna

Manager - SaaS Operations

Office: 1-*619-629-0325*
[image: Hookit.com] <http://www.hookit.com/>

[image: Hookit on Facebook] <https://www.facebook.com/hookit/> [image:
Hookit on Instagram] <https://www.instagram.com/hookit/>  [image: Hookit on
Twitter] <https://twitter.com/hookitcom>  [image: Hookit on Medium]
<https://medium.com/@hookit>  [image: Hookit on LinkedIn]
<https://www.linkedin.com/company/hookit-com/>

**Comment by ljay79** [comment]
Are you guys using Microsoft single-login or just regular atlassian accounts?
All of you use the Api Token authentication with my add-on?

**Comment by wyojoe** [comment]
We're just  using the regular atlassian accounts

I'm the only one that uses the add-on and I use the Api Token
authentication.


Joe Taberna

Manager - SaaS Operations

Office: 1-*619-629-0325*
[image: Hookit.com] <http://www.hookit.com/>

[image: Hookit on Facebook] <https://www.facebook.com/hookit/> [image:
Hookit on Instagram] <https://www.instagram.com/hookit/>  [image: Hookit on
Twitter] <https://twitter.com/hookitcom>  [image: Hookit on Medium]
<https://medium.com/@hookit>  [image: Hookit on LinkedIn]
<https://www.linkedin.com/company/hookit-com/>

**Comment by titusfvr** [comment]
Regular Atlassian accounts here.
I'm the only one using & trying to implement it and I use the API Token authentication.

**Comment by ljay79** [comment]
Any of you guys who experiencing this issue, could you help me investigate this and turn on debugging for me pls.

Please enable the debugging, take note of the temp. user key and post it here, then perform at least once the dialog to get the filters so it is causing the error.

Please report back to me with your user key and the time frame your executed it.
As for now, i have some logs, but usually before or after you guys enable debugging. And so far i have only 2 user keys, both indicate 2 complete different reasons/issues. 

@nelsonology logs indicate the retrieval of your filters is responded by jira without a valid JSON dataset. I will need more debugging info and your help to get deeper.

@wyojoe without enabled debugging during a failed test scenario, i can only guess from error logs around that time which indicate an not conform JSON response, the filter owners appear to have no _displayName_ on them.

If you could assist by providing above procedures, i would appricate and be able to investigate further.

BTW: Is one of you guys a little bit familiar with JSON data and/or curl requests? That could enable further debugging info. I would provide some instructions if you like.

**Comment by wyojoe** [comment]
Debugging on, tried to create IssueTable from filter at the time of 17:42
Temp. User
Key:ALEt7zQa8BP7fqCtgX4yX9DD1pyBIRI9WTDqfl0SuJFcRi3vZBWZ0bTP3BUCDCCTqbc2VHafQj8Q






Joe Taberna

Manager - SaaS Operations

Office: 1-*619-629-0325*
[image: Hookit.com] <http://www.hookit.com/>

[image: Hookit on Facebook] <https://www.facebook.com/hookit/> [image:
Hookit on Instagram] <https://www.instagram.com/hookit/>  [image: Hookit on
Twitter] <https://twitter.com/hookitcom>  [image: Hookit on Medium]
<https://medium.com/@hookit>  [image: Hookit on LinkedIn]
<https://www.linkedin.com/company/hookit-com/>

**Comment by ljay79** [comment]
Thank you @wyojoe that was really helpful.
I can now confirm, that the Jira api is responding your filters however is missing the "owner" part for each of these filers. Which should not happen by API definition response object.

I can now work on that issue and implement some validations as well checking for the latest api deprecation notice i found.
It might take some days to implement a proper update, but i will keep you updated.

**Comment by wyojoe** [comment]
Awesome! Thank you so much for your help.


Joe Taberna

Manager - SaaS Operations

Office: 1-*619-629-0325*
[image: Hookit.com] <http://www.hookit.com/>

[image: Hookit on Facebook] <https://www.facebook.com/hookit/> [image:
Hookit on Instagram] <https://www.instagram.com/hookit/>  [image: Hookit on
Twitter] <https://twitter.com/hookitcom>  [image: Hookit on Medium]
<https://medium.com/@hookit>  [image: Hookit on LinkedIn]
<https://www.linkedin.com/company/hookit-com/>

**Comment by ljay79** [comment]
I have just released a fix as i believe: v1.4.6 #260 

Please check and let me know if it fixes your issue.

**Comment by wyojoe** [comment]
That fixed it!
Thank you so much.


Joe Taberna

Manager - SaaS Operations

Office: 1-*619-629-0325*
[image: Hookit.com] <http://www.hookit.com/>

[image: Hookit on Facebook] <https://www.facebook.com/hookit/> [image:
Hookit on Instagram] <https://www.instagram.com/hookit/>  [image: Hookit on
Twitter] <https://twitter.com/hookitcom>  [image: Hookit on Medium]
<https://medium.com/@hookit>  [image: Hookit on LinkedIn]
<https://www.linkedin.com/company/hookit-com/>

**Comment by ljay79** [comment]
Awesome, I would appreciate any good review/feedback in the Google's marketplaces like:
https://gsuite.google.com/marketplace/app/project_aid_for_jira/248954272770

@titusfvr and @nelsonology has the issue been resolved for you as well?
