### ISSUE TITLE
Add-ons > Project Aid for Jira greyed out

### ISSUE THREAD

**Issue by jasonmadigan** [ljay79/jira-tools#256]
After installing, Add-ons > Project Aid for Jira is greyed out

![Screenshot 2020-06-09 at 09 38 25](https://user-images.githubusercontent.com/4467/84125862-11fcf300-aa35-11ea-885e-c8f884ccc1f8.png)

** Provide Debugging information **
For further investigation, please activate Debugging in "About" dialog, provide us with your "Temp. User Key" and then perform at least one another try. This way it will log the error and debug information to project owners StackDriver logging account where we can analyze it better.
>Note: User credentials are not transmitted in any log data.

Can't get into this menu, the whole item is greyed out.

### Steps to reproduce
** Provide a set of unambiguous steps to reproduce this bug include code, if relevant **
1.
2.
3.

### Expected result
** Tell us what should happen **
1.

### Actual result
** Tell us what happens instead **
1. [Screenshot, logs]

**Comment by ljay79** [comment]
Hi @jasonmadigan 

never saw a greyed out add-on listing in the menu before.
Did you completed the authorization process during the installation?
Did you try to reload the browser / sheet ?

**Comment by jasonmadigan** [comment]
Yes, authorization worked OK, no errors after enabling. Very strange. Could be related to some specific org permissions for gSuite?

**Comment by ljay79** [comment]
hmmm strange. Org permission could be a reason, not really familiar with it. But it should give a hint or anything i would expect. Any "?" icon there? Can you open your "Manage add-ons" and see what it tells you there for this add-on.

**Comment by jasonmadigan** [comment]
Seems to be OK under "Managed add-ons". Screenshot:

![Screenshot 2020-06-09 at 12 19 03](https://user-images.githubusercontent.com/4467/84141682-7a56cf00-aa4b-11ea-8929-cc20d0861507.png)

**Comment by ljay79** [comment]
Strange. Can you create a complete new Document and see if there is any difference.

**Comment by jasonmadigan** [comment]
New doc, seems the same.

![Screenshot 2020-06-09 at 12 34 53](https://user-images.githubusercontent.com/4467/84142973-aa9f6d00-aa4d-11ea-95ce-c5fe0562852e.png)

**Comment by ljay79** [comment]
Very strange. Sorry, as of now i have no freakn idea why this is inactive.

Its all try & error :)
- uninstall / reinstall
- verify permissions of the document
- try installing any other add-on if thats a common issue on other add-ons too
- maybe even check with your G-Suite Admin if there is any restriction which could cause this

Sorry that i cant be of much help yet. I hope you find the reason and will update here when found.

**Comment by jasonmadigan** [comment]
I'll keep digging and contact a G-Suite admin if I get nowhere, looks to be something perms related if I was to guess!

**Comment by jasonmadigan** [comment]
It was an G-Suite admin permissions thing (don't have any more detail I'm afraid). Closing this.
