### ISSUE TITLE
Unexpected token error when I try to update

### ISSUE THREAD

**Issue by marianallr** [ljay79/jira-tools#258]
Settings show me a "connection successfully stablished" but when I try to refresh a table it is not working, it doesn't detect the sheet has a table. And when it does, I click on "refresh" and nothing happens. 
When I tried to create a new table, I saw an error on the top of the screen saying "SyntaxError: Unexpected token: o" 

I have been using the tool for 2 weeks without an issue, even today earlier, but now I'm not able to make it work in any sheet. 
Can you help? Thanks!

![image](https://user-images.githubusercontent.com/9891032/84455409-acc32080-ac33-11ea-96de-189002ff6de0.png)

**Comment by melissa-thompson** [comment]
Yes, I'm getting the same error today. 
It looks like a commit was done around 6 hours ago. Could that have broken something?

**Comment by snehkumar83** [comment]
Hi, I am also facing the same issue from sometime, today. Any idea by when this issue will be resolved.

**Comment by ljay79** [comment]
Hi. I have just published the pervious vesion.
Will investigate the issue on the new update.

Could you guys pls provide me with the "temp user key" which you can find in the "About" menu dialog.

**Comment by ljay79** [comment]
I hope i could solve this new bug introduced by a improvement for #255 .
Hopefully this time without new issues.

Pls let me know, if you expirience any new issue with this lastest version v1.4.5

**Comment by marianallr** [comment]
Hi Jens, 
The day after I submitted this ticket, the problem was solved. I've been using it without issues since then. That particular day I refreshed the tables more times than I usually do...so, do you think that could have been part of the issue?
I will let you know if the issue happens again, _danke shön_ for taking a look!

**Comment by ljay79** [comment]
Hi. The issue occured due to a missing version compatibility on a part I was working for #255 which I now solved in latest update .

I had figured out,why you guys got that error and believe I have solved it.
