### ISSUE TITLE
Create issuetable from filter doesn't display the whole list of filters

### ISSUE THREAD

**Issue by simonjaz** [ljay79/jira-tools#262]
** Provide a general summary of the issue in the Title above **
Create issuetable from filter doesn't display the whole list of filters
** Provide a more detailed information of the issue **
When I get the list of available filters it doesn't list all the filters I have in Jira. Not sure why, but I'm missing my filters for my user in Jira.

** Provide Debugging information **
For further investigation, please activate Debugging in "About" dialog, provide us with your "Temp. User Key" and then perform at least one another try. This way it will log the error and debug information to project owners StackDriver logging account where we can analyze it better.
>Note: User credentials are not transmitted in any log data.
ALEt7zTUuZLeP3kxMv75iYScrfPou5RsdW+jyykuX4su/3ZxK328a9zOGYONuag1m7ftbyzkAMkf

### Steps to reproduce
** Provide a set of unambiguous steps to reproduce this bug include code, if relevant **
1.
2.
3.

### Expected result
** Tell us what should happen **
1. List all the available filters for the user.

### Actual result
** Tell us what happens instead **
1. [Screenshot, logs]

**Comment by ljay79** [comment]
Hi.
How many filters are you seeing and how many do you expect to see?
Are you using Jira Cloud or Server?

**Comment by ljay79** [comment]
Hi @simonjaz  again,
i had a look at your logs... if im not mistken, you have about *904* filters! Can that be right?!
At this point, i just assume, my script for that part can simple not handle that many filters. Its also quite insufficient to list them in a dropdown there.

Please try to clean up your list of filters in Jira if ever possible.

BTW: Are you really using all these filters? Maybe its time to wipe the broom and get rid of - lets say - 800 filters :)

**Comment by ljay79** [comment]
With the latest version i have just release #266 (v1.4.7) you will now find the option in that dialog to list only your own personally owned filters rather than all you have access to.

Hope this helps.

**Comment by simonjaz** [comment]
@ljay79 sorry for late answer. I missed your comment since I was on vacation :) Thank you for your solution - I agree, having all those filters doesn't help, we need to clean them up, but option to list personally owned will fix this issue for me, for now :) Thanks once again!
