### ISSUE TITLE
Assignee changes to "Unassigned"

### ISSUE THREAD

**Issue by NonTechGuy** [ljay79/jira-tools#264]
** Assignee changes to "Unassigned" **

** When selecting Project Aid for Jira > Update Jira Issues assignee displays as unassigned**

** Provide Debugging information **
For further investigation, please activate Debugging in "About" dialog, provide us with your "Temp. User Key" and then perform at least one another try. This way it will log the error and debug information to project owners StackDriver logging account where we can analyze it better.
>Note: User credentials are not transmitted in any log data.

### Steps to reproduce
** Provide a set of unambiguous steps to reproduce this bug include code, if relevant **
1. Make sure to import issues from jira 
2. Don't change the assignee in the assignee column
3. Select Add-ons
4. Select Project Aid for Jira
5. Select Update Jira Issues
6. Configure the columns and Jira fields
7. Check Assignee and select Assignee from the dropdown
8. In Jira assignee has changed to "Unassigned"

### Expected result
** Tell us what should happen **
1. In Jira
2. The Assignee should remain unchanged

### Actual result
** Tell us what happens instead **
1. 1. In Jira
2. The Assignee has been changed to "Unassigned"

<img width="486" alt="Screenshot 2020-07-08 at 13 58 41" src="https://user-images.githubusercontent.com/5426828/86916067-50b0c680-c123-11ea-8fe4-0b64a7ff4f96.png">
<img width="1145" alt="Screenshot 2020-07-08 at 13 59 32" src="https://user-images.githubusercontent.com/5426828/86916432-dfbdde80-c123-11ea-9f1d-9b21a3a97b61.png">

**Comment by ljay79** [comment]
Hi @NonTechGuy 
Thx for reporting your issue.
I see u have closed it already, how come?

**Comment by NonTechGuy** [comment]
Hi, I was using the Jira Cloud for sheets add-on to get the data from Jira and then using the Project Aid for Jira add-on to push the changes to Jira. I didn't realise that Project Aid for Jira pulled through filtered results from Jira too. It was only once I read the docs that I realised my mistake.
