### ISSUE TITLE
Project Aid for Jira missing from google sheet add-ons

### ISSUE THREAD

**Issue by arenfrew** [ljay79/jira-tools#268]
** Provide a general summary of the issue in the Title above **
It seems like since this afternoon, the add-on has been completely missing from google sheets/suite marketplace.

** Provide a more detailed information of the issue **
I can't find the add-on on any sheets that previously had it installed, and it's missing when searching for it in the marketplace (despite auto filling in the search bar).  The [direct link](https://gsuite.google.com/marketplace/app/project_aid_for_jira/) found when googling for Project Aid leads to a 404.  I noticed an update to the repo at around the same time the add-on was removed, perhaps that's related?

** Provide Debugging information **
For further investigation, please activate Debugging in "About" dialog, provide us with your "Temp. User Key" and then perform at least one another try. This way it will log the error and debug information to project owners StackDriver logging account where we can analyze it better.
>Note: User credentials are not transmitted in any log data.

I don't believe anything else on this actually applies.  Normally I would posit this inquiry to the marketplace listing, but as stated above it is unavailable there.

### Steps to reproduce
** Provide a set of unambiguous steps to reproduce this bug include code, if relevant **
1.
2.
3.

### Expected result
** Tell us what should happen **
1.

### Actual result
** Tell us what happens instead **
1. [Screenshot, logs]

**Comment by ljay79** [comment]
Yes, sorry. While publishing an update I clicked a button 10pixel next to it which was called "unpublished" without any confirmation prompt;(

Now the app is sadly unpublished until Google performs again a review and publishes it.

I'm so sorry. My mistake on a bad user google user interface. I can't speed it up, have to rely on google team releasing it asap. ;(

**Comment by arenfrew** [comment]
Ah, that explains it!  Thanks so much for the quick response, hopefully they hurry the process along.  Also, thanks so much for your work on this tool, it's a real life saver!

**Comment by snehkumar83** [comment]
Any idea, In general how much time google team takes to review and release.

**Comment by ljay79** [comment]
Sadly not. Its typical Google (support). Anything between hours and weeks :(

I hope its live during today...

**Comment by MaximOrlovsky** [comment]
Thanks for the quick update. I hope Google will publish it ASAP.

**Comment by petermcgurkesw** [comment]
Glad to know project aid is not gone forever!  I found it incredibly useful for my work and I hope Google republish it soon!

**Comment by ljay79** [comment]
Oh man, this google review process might take longer than expected! :((((((((

They just (after about 24h) reached out to me, and explained they are now starting the review, asking for test credentials (difficult with Jira dependency) and opened a "review feedback" document. OMG :(

Pls just release the add-on, which was public for years...

Sorry guys for my accident! I might pay with loss of lots of users now ;(

**Comment by ljay79** [comment]
Yeahy the add-on is officially back online and available.
