### ISSUE TITLE
Generate time report doesnt generate any time

### ISSUE THREAD

**Issue by jbozic1** [ljay79/jira-tools#273]
When i generate time report using layout using layout Issues -> Dates it gets good tasks but values are always 0
When i generate using layout Dates -> Issues it generates only headers.
It's JIRA Cloud

**Comment by ljay79** [comment]
Hi @jbozic1 
i just tested myself and it was working fine.

For further investigation, please activate Debugging in "About" dialog, provide us with your "Temp. User Key" and then perform at least one another try. This way it will log the error and debug information to project owners StackDriver logging account where we can analyze it better.
>Note: User credentials are not transmitted in any log data.

**Comment by jbozic1** [comment]
My temp user key is : ALEt7zT2MIwidUc0750Th8t6XQ/R0beBAHJZuBC0TTpXpBZohCB0tDsPhePhuI53oYfir/psBe15
I tried again, and now Issues -> Dates case is working, i can see values, but Dates -> Issues doesn't show anything except headers.
Thank you for quick response.

**Comment by ljay79** [comment]
according to the logs, the failing requests to not include any username.

For a more detailed view on my logs here, can you please do the following:
* take note of the time frame and report to me
* turn on debugging 
* performs onces the failing use case
* turn off debugging
* report back to me :)

This way i can take a look at a specific time period and the logs.
Please make sure, when u enter the username, you do also select the user from the dropdown not only entering the full name.

**Comment by jbozic1** [comment]
Time 11:03 -> 11:06 (Croatia)
Everything works now, yesterday few times i tried Issues -> Dates case didn't work (it got user, issues, but no data)
I will close not this, because at this moment it works fine, if i get another issue I'll do as recommended an reopen this.
Thank you for your time.
