### ISSUE TITLE
Custom Function toggle not working

### ISSUE THREAD

**Issue by freddeichler** [ljay79/jira-tools#274]
** Provide a general summary of the issue in the Title above **
When using the custom formula JST_getTotalForSearchResult I am getting an error that custom functions must be enabled. This toggle is enabled.
![Screen Shot 2020-08-27 at 10 50 53 AM](https://user-images.githubusercontent.com/59850633/91465273-348ff280-e853-11ea-9460-4b16e24c968b.png)

** Provide a more detailed information of the issue **
I'm trying to get the total for a JQL and I'm getting an error that I need to enable custom functions. I have disabled and reenabled custom functions a few times and the error persists.

I also checked that my Jira integration is working fine and I can retrieve custom fields.
![Screen Shot 2020-08-27 at 12 34 58 PM](https://user-images.githubusercontent.com/59850633/91475815-bbe46280-e861-11ea-8615-8f3263570de0.png)

** Provide Debugging information **
For further investigation, please activate Debugging in "About" dialog, provide us with your "Temp. User Key" and then perform at least one another try. This way it will log the error and debug information to project owners StackDriver logging account where we can analyze it better.
>Note: User credentials are not transmitted in any log data.

ALEt7zRSi+SqSh/36M1qOXKOAKLNxXGiZknEUfNJyzfh1JJVzvhHNhXiKB7FQD3D0W3MkPrEfLJ0

### Steps to reproduce
** Provide a set of unambiguous steps to reproduce this bug include code, if relevant **
1. enter =JST_getTotalForSearchResult("status = done") into a cell
2. hit return
3. !#ERROR is in the cell and the popover says that custom functions must be enabled

### Expected result
** Tell us what should happen **
1. I would expect the total issue count

### Actual result
** Tell us what happens instead **
1. Error
Error: The document owner (you) must enable custom functions. Open 'Add-ons > Project Aid for Jira > Settings' and toggle 'Custom Functions' to enabled. If you are not the document owner, ask him to enable custom functions. (line 202).
![Screen Shot 2020-08-27 at 10 46 15 AM](https://user-images.githubusercontent.com/59850633/91465232-26da6d00-e853-11ea-81c4-b74e792a9f03.png)

**Comment by ljay79** [comment]
Hi @freddeichler sry, i didnt find time before.
I couldnt find any debug logs for your case during the expected time period.

May you please enable debugging and perform this action again, so i will get fresh logs.

**Comment by freddeichler** [comment]
Hello @ljay79 ,

Thank you for your response. I turned the debug off and then on again, here is the Temp. User:

ALEt7zRSi+SqSh/36M1qOXKOAKLNxXGiZknEUfNJyzfh1JJVzvhHNhXiKB7FQD3D0W3MkPrEfLJ0

I then just attempted this command: =JST_getTotalForSearchResult("status = Done") and got the same result as I have been getting.

**Comment by ljay79** [comment]
sry for my first comment, i was wrong. Have a lot of logs :/

**Comment by ljay79** [comment]
I can see you disable and re-enabled debugging. After that, no logs ..

**Comment by freddeichler** [comment]
Strange, I just updated the function again

**Comment by freddeichler** [comment]
I was able to get a workaround just now for what I needed using ImportJSON

**Comment by ljay79** [comment]
hmmm the last debug log was from 18:32 GTM just logging that you switched on the debugging. Since then, no log for the provided user key.

**Comment by freddeichler** [comment]
ok, I tried another formula.

**Comment by ljay79** [comment]
hmmm nothing... can you verify the temp user key didnt change...

**Comment by ljay79** [comment]
whenever you have time, please reinstall the add-on, create a new spreadsheet, enable debugging, take note of the temp user key and perform the troubling action again.

**Comment by freddeichler** [comment]
I removed the add-on, created a new spreadsheet, added the add-on, and it is now working. Thank you for your persistence. 

Thanks for

**Comment by ljay79** [comment]
Im glad its working now. I will close this issue then.
