### ISSUE TITLE
Create issue table from filter not working properly

### ISSUE THREAD

**Issue by leaannegaffney** [ljay79/jira-tools#275]
I have only recently started using this tool and have yet to successfully pull issues into my google sheet from a Jira filter. I think the connection is set up properly as I am able to update an issue key status, and I can also see my Jira filters so it is connecting to my Jira account. The problem is that when I try to create an issue table from a filter nothing is happening and I am seeing what's in the image below which never changes until it either times out or I have to go and manually delete the file. 
![Screenshot 2020-09-03 at 11 49 54](https://user-images.githubusercontent.com/43925441/92129886-ff0f7a00-edfb-11ea-9c52-a939bd408c17.png)

I tried to find a solution and while I was looking at the console logs trying to figure out what might be the issue, I noticed the below error popping up every time I tried to create the issue table from a filter. 
![Screenshot 2020-09-03 at 12 08 31](https://user-images.githubusercontent.com/43925441/92130481-b1474180-edfc-11ea-852d-c5e25fc78296.png)

After a bit of reading around CORS and 'No-Access-Control-Origin' header I think this may be the cause of the problem. I am working with Jira Server also if that is any help to you. If you need any more information from me please let me know. 

Thank you!

**Comment by ljay79** [comment]
Hi @leaannegaffney 
The CORS issue seems unrelated to the addon itself.

The screenshot above, does show it, do you get any filters listed at all?
The status bar on lower right showing "..fetching page 2/200" indicates you have a process running in the background fetching a filter result.

To better reproduce and analyze the issue; please
- create a complete new Spreadsheet
- choose "Create IssueTable from filter"
- wait for the filter list to be shown
- choose a filter where you know (or expect) only a few 10 to 20 results at best

For better debugging on my end, i would like to request you enable debugging in the add-ons "About" dialog and provide me with the shown "temp user key".

**Comment by leaannegaffney** [comment]
Hi @ljay79 
Yes I get all of my Jira filters listed, apologies I couldn't include them in the screenshot for privacy reasons. It never pulls in the issues from the filter though. 

The temp user key is ALEt7zTQE8zPk10KrR+wvt5gqaB4pMLU4zOBwFZWO1adQwmPtwN0ukJH/SieL4yWuYaqjes+2Xhv

I had already created a specific filter to test with which should produce about 10 results so I've chosen that again with the debugging enabled like you requested. 

Thanks for your help

**Comment by leaannegaffney** [comment]
I have noticed that when I try to run the filter a second time in the same spreadsheet, an exception message pops up saying an address is unavailable. Once I click ok it pulls in lots of random issues from the same organisation but are not related to the project my filter should be querying. 

Also it may be worth mentioning that a colleague is getting the exact same errors on his machine when he tries to create an issue table from his filter

**Comment by ljay79** [comment]
Thx for the update @leaannegaffney 
Could you stil elaborate the root cause please.

You mentioned the connection was working and you were able to pull some data but not all due to a typo in your URL?

If i understand the issue, i might be able to improve the setup procedure to prevent such issues in the future.

**Comment by leaannegaffney** [comment]
I'm not 100% sure what the root cause of the issue was. The original URL I was using was a more general Jira URL for my organisation so it think the issue was that the URL wasn't specific to the project I wanted to query. 

When setting up the Add-On I found it a bit confusing and didn't know what specific URL I should use. When I saw that my filters were listed and the connection was successful I didn't really consider that the URL could be wrong, when in fact that was the issue. 

If you want to try and prevent this in the future, maybe more information around the setup and which URL to use would have helped a lot. 

I hope that answers your question.

**Comment by ljay79** [comment]
Thx for the feedback. What URL do you use now? You can leave out the domain part if you like.
What Jira Version and Type (Cloud or Server) do you use.

**Comment by leaannegaffney** [comment]
So the current URL looks like this https://subdomain.topleveldomain.com 

Jira Server, Version 7.13.8

**Comment by ljay79** [comment]
Hmmm, thats also what the Settings form gives as an example _(ie: https://mysite.atlassian.net/)_
Not sure how to make this more clear :)

What did you enter then in first place, which wasnt working..

**Comment by leaannegaffney** [comment]
I entered the same subdomain but a different top level domain so the previous URL looked like this https://subdomain.topleveldomain.org. It's probably not something that will cause issues for anyone else but it was figuring out the right URL to use that caused me the confusion anyway. 

Thanks again

**Comment by ljay79** [comment]
Got ya. That seems like a specific issue to your custom server setup, that you have multple domains/urls available.
Thanks for clarification.

PS: Im always happy to see good reviews on the add-on in the Google Marketplace :)
https://gsuite.google.com/marketplace/app/project_aid_for_jira/248954272770
