### ISSUE TITLE
Refresh IssueTable problem

### ISSUE THREAD

**Issue by noraszel** [ljay79/jira-tools#277]
** I cannot refresh my IssueTables **

I have some GoogleSheets, where I use the "Project Aid for JIRA Issue table from filter” function. (I use these tables for sources to some automated reports.)
Usually I refresh these tables every day, but now after I created new Google sheets from earlier templates and I try to create new Issue tables from new filters I cannot refresh them.
When I try to use the "Refresh Issue Table" function the add-on cannot remember my tables, it shows me this message: "You do not have any Jira "IssueTable" in your current sheet(s)...." (I created a screenshot of one of these tables).

So the steps:
1. I had a report Google Sheet table (for previous iteration) with Project Aid Issue tables from filter.
2. I copied this Google Sheet.
3. I deleted the data from the Issue tables (from that Sheets were the Issue tables were) and I created new tables from new filters (on the same sheets, with the same sheet names, because the other sheets use these names).

When I realised the refresh problem, I tried another way:
1. I created a brand new Google Sheet table.
2. I created some JIRA Issue table source sheets from the new JIRA filters on brand new sheets. (I named them like the previous ones because of the links.)
3. I copied only the report sheets (which contain many formulas and many links to these JIRA Issue tables, but not contain Project Aid JIRA Issue table).

And the problem is the same with both scenarios.

So could you help me? How can I solve this problem?

<img width="1432" alt="Screenshot 2020-10-28 at 13 59 35" src="https://user-images.githubusercontent.com/60604822/97441972-9dfeb100-1929-11eb-9f1f-458fbe75e234.png">

**Comment by Darrin-BC** [comment]
I am having the same issue.  I create an issue table, then come back the next day to refresh and it says that I don't have an issue table on the sheet.

**Comment by ljay79** [comment]
Can you please provide debugging infirmation.
Please activate Debugging in "About" dialog, provide me with your "Temp. User Key" and then perform at least one another try. This way it will log the error and debug information to my StackDriver logging account where I can analyze it better.
>Note: User credentials are not transmitted in any log data.

If you perform the debug scenario, please use a clean new sheet, try to perform just the relevant actions. It will limit the debug info to just the relevant stuff. Turn on debugging just before the actions and turn it back off again right after.

Please also provide me with a rough time frame you performed the test. It will speed up my search in the logs :)

**Comment by Darrin-BC** [comment]
ALEt7zSFvPffNhNENi3IPRf3iJq6p9zfG2247LLKp7LZxz/ThDS0T5gnnpmMTqGjLEUaXSq/SBEH - temp user key
I performed the update on November 11th at 3:47pm US Central Time.  I could not use a new sheet because it usually takes a day for the reference table to be "forgotten".  I did create a new sheet that I will test tomorrow.

This is what it tells me
![image](https://user-images.githubusercontent.com/68078081/98868468-c8766100-2435-11eb-83e0-59784d6afe4c.png)

**Comment by noraszel** [comment]
Hi @ljay79,
I tested again.
1. First, I switched off the Debugging function, because it was switched on because of another earlier issue.
2. I created a brand new spreadsheet with 4 sheets and I created an issue table for each of them.
3. I switched on the Debugging function and I tried to refresh them, but I couldn't. The message is the same then before.
4. I switched off the Debugging function again.
The test was 5 minutes.
My user key is: ALEt7zQ8rhxZ61+C+DpdLzJdiMcBB4OdhQzG0zjx4Gk3048vbJHbxSWbM0uig6sjH+hsHDMB+Zb3

Thanks your work!
Nora

**Comment by ljay79** [comment]
Thx to both of you. Apparently i am now able to reproduce the issue.
I will investigate the reason for this any report back..

**Comment by ljay79** [comment]
Sorry that it took so long.
I believe i was able to provide a BugFix for this issue which i have just released to the Google Store.

Your add-on is updated when it shows "version 1.4.8" in the about dialog.

Please let me know, if the issue has been solved for you.

**Comment by noraszel** [comment]
It is working again! Thank you very much! :)
