### ISSUE TITLE
Unable to access Jira server after moving to VPC

### ISSUE THREAD

**Issue by rake23** [ljay79/jira-tools#279]
Our Jira server is moved to VPC in AWS. So now we can't use over the public internet and it is accessible only in the office network or in a VPN. Now we are facing issues using the plugin. It's not connecting anymore. Tried with and without a VPN. No luck. Any help is appreciated. 

![image](https://user-images.githubusercontent.com/28426859/98777871-80e0dc80-2417-11eb-894f-fa097a981572.png)

**Comment by ljay79** [comment]
If the JIRA installation is not publicly reachable, then it wont work.
The Sheet Addon will perform connection from your client browser and from within googles network (public).

The mentioned domain above, for me, seems not publicly available at all, so the add-on wont be able to reach the API neither.

**Comment by rake23** [comment]
Thanks for checking. I will check with our IT support team.

**Comment by ankitsinghalsr** [comment]
Hello Team,

Facing the same issue, as per the IT team, if we can get the IP of the server add on is calling the api from, and if we can get it whitelisted then it would work.

Can you please share the IP, so that we can give it a try.

**Comment by ljay79** [comment]
I doubt you will have any luck on this approach, unless you whitelist the relevant google IPs (which i have no clue to find an overview).

That add-on, as any Google Docs/Sheet add-on is a cloud based solution.
It runs in same environment as any other default google sheet functionality. That add-on has no control on where it runs or what IP it is using or anything.

**Comment by ankitsinghalsr** [comment]
Thanks for prompt reply.

I already got the Google's ip whitelisted(got them from google support), still does not work.

Appreciate your response.

**Comment by ljay79** [comment]
Hmm maybe not the correct IPs ?! I dont know, i never tried to do this. When u have network sniffer you might be able to identify the actual sources connecting to the Jira. Keep in mind, its cloud based, so IPs are varying.
