### ISSUE TITLE
Address unavailable after Jira upgrade

### ISSUE THREAD

**Issue by yashwanth-n** [ljay79/jira-tools#280]
Recently we upgraded our Jira Server. New version is ( v8.5.8#805008-sha1:b678804 ) .

After upgrade the links are not working and consistently get address not unavailable error.

Example :-
Exception: Address unavailable: https://jira.urjanet.net/rest/api/2/filter/favourite

### Steps to reproduce
** Provide a set of unambiguous steps to reproduce this bug include code, if relevant **
1. Open spreadsheet plugin
2. On new sheet, choose the Create table from filter option
3. Error is thrown

### Expected result
** Tell us what should happen **
1. Should show filters

### Actual result
** Tell us what happens instead **
1. Exception: Address unavailable: https://jira.urjanet.net/rest/api/2/filter/favourite

**Comment by ljay79** [comment]
please see #279 , one of your teammates reported the issue already.
