### ISSUE TITLE
"Refresh Ticket Data"

### ISSUE THREAD

**Issue by simonjaz** [ljay79/jira-tools#30]
Hi, is there a way you could update statuses of Jira tickets in column Status if you have it in Google spreadsheets?
Now it updates current Jira ticket id, but I think it would be useful to just update Status field. Additionally even better would be to just update all those fields that you have in columns you got with "List Issues From Filter" function.

**Comment by ljay79** [comment]
Hi @simonjaz ,

i would love to do, however google sheet doesnt allow to reference cells in any way. This makes its kinda impossible to me to find the related cell which inherits just the status string for a particular jira ticket cell.
Updating the issues from "List issues from Filter" you can only really do by overwriting the current table with entire new one from filter.  

Sry.

As soon this referencing of table cells is one day somehow possible, i will be glad to implement such functionality.
