### ISSUE TITLE
Add Custom Fields

### ISSUE THREAD

**Issue by juliangardnereurocios** [ljay79/jira-tools#31]
Hi,

I'm looking for a good plugin that will allow me to have results from a JIRA filter in a Google Sheet. Yours would be perfect, if we were able to show custom fields, like "sprint", but also our own custom fields.

Do you think this is possible?

Your,

Julian

**Comment by ljay79** [comment]
Hi @juliangardnereurocios 
thanks for the feedback. I have this feature for custom fields already on my roadmap.
Cant tell when, but maybe before end of september...

**Comment by fmccross** [comment]
I agree with this enhancement. The tool is great and exactly what I've been looking for but need to be able to import custom fields too.

**Comment by ljay79** [comment]
Thx for the feedback @fmccross i definitivly will add such functionality.
Its a little tricky though and will require a little time for me... but ofcourse i let you know here on any updates..

**Comment by ebiss** [comment]
Sounds like you've already got this one in the works, but I'd like to reiterate how amazingly helpful this feature would be! We just started using the add-on and love it, but are blocked on building the charts that we need until we can pull in a custom date time field that we created in JIRA.

**Comment by ljay79** [comment]
Quick update:

I am in progress of implementing support for Custom Fields at this moment.
I guess, within 1 or 2 weeks i should be able to release and new version.

One little bummer however, the Add-On wont be able to support any type of custom Jira fields.
For the moment i will only be able to provide support to custom fields of schema type: _date_, _datetime_, _string_ and _number_
Any other types i cant think of on how to support such as many of them use some JAVA internal jira types which im unable to read the value/formats over the REST API.

In the future however, i might be able to extend support for (standard) types like "checkbox" or "dropdown".

... stay tuned

**Comment by JOPE51** [comment]
I follow the comment of EBISS.  Also for us, it can be a great help to organise our project planning

**Comment by ljay79** [comment]
Thx. Im only waiting for some visual tweaks then we are ready for a new release...

**Comment by ljay79** [comment]
New version 0.19.0 (GA version 12) is now available in Google Add-On Store and approved already.
Should be automatically update in your sheet within next 24 hours.

Check the "About" dialog within the Add-On to verify what version is installed.

**Comment by JOPE51** [comment]
I tried the new release (checked it in the "About").  The problem is that when I try to configure custom fields I get the message 'No custom fields available! (red box in pop up). Can you tell me what the problem is? Do I have to make a new connection between JIRA and Google sheet? Do I have to change (define) something within JIRA itself?

**Comment by ljay79** [comment]
Hmmm no. You shouldnt have to do anything. Is is fetching all custom fields via jira rest api. I'll see if i can reproduce or analyze somehow.

**Comment by ljay79** [comment]
Can you do me 2 favours please:
a) open up a new issues (bug) with the report
b) go into the About dialog of my add-on and pass me on the value right next to the label "Temp. User Key".

This key is a temporary session key of a user running the script and allows me to filter for any error logs / stacktraces in the google StackDriver logs.
It is not disclosing any sensitive information of yours.

**Comment by JOPE51** [comment]
If I understood well, then this should be the key : 
AFikiF3kacGA6pAvuI8V/4ANnTV2NhFiMxbgPuSSBYnX38SR+9GUuWEEXNAs4PUKDcf+PU3cKHnG

**Comment by juliangardnereurocios** [comment]
This works perfectly for us, thank you for the work!
