### ISSUE TITLE
Ability to run jql counts

### ISSUE THREAD

**Issue by gzsombor** [ljay79/jira-tools#33]
It would be nice, if the user could write custom queries into the sheets.
For example JIRA_COUNT("project = SOMETHING AND resolution = Unresolved AND assignee = xyz")
What do you think? Is it reasonable / simple thing to implement?

**Comment by ljay79** [comment]
Hi @gzsombor,
Thx for your feedback.
I think this kind of direct JQL integration is beyond the scope of this add-on. Sry
