### ISSUE TITLE
Tool only lists 100 issues

### ISSUE THREAD

**Issue by nahuelio93** [ljay79/jira-tools#34]
Hey, I've been using the tool fine so far but it suddenly started only updating the last 100 issues on the filte (list issues from filter)r. I've tried with new filters and with another account and PC but to no avail. Is there a way to go back to having more tickets listed?

**Comment by ljay79** [comment]
Hi @nahuelio93 

i can reproduce this and confirm. All my filter are limited to a result set of max 100 even the add-on has a value of 1000 passing to Jira's api.

I found an article from JIRA, just recently updated, which might explain why:
https://confluence.atlassian.com/jirakb/changing-maxresults-parameter-for-jira-rest-api-779160706.html

As i have started with an actual pagination implementation - as suggested by Atlassian - i will jump on a proper fix for this as soon as possible.
Pls check back in a few days...

Sry for the inconvenience, at this point i believe that Atlassian did actually changed the API to forcefully limit such requests to max 100 regardless if i pass in a proper param with a higher value.

**Comment by ljay79** [comment]
Little Update.

Im do quite well progress. Paginated search result is working on my DEV already even with more than 3000 jira issues to list - requires a lot from my chrome performance :)

I have to do some hardning and fine tuning, as well as have @DanielKulbe go over the visuals and then im pretty sure, beginning next week i can release a update release with a proper solution and some new feature.

**Comment by nahuelio93** [comment]
Great! Thanks for the quick and complete response!

**Comment by ljay79** [comment]
New version 0.19.0 (GA version 12) is now available in Google Add-On Store and approved already.
Should be automatically update in your sheet within next 24 hours.

Check the "About" dialog within the Add-On to verify what version is installed.
