### ISSUE TITLE
Chrome Manage add-ons - "Remove" and "Use in this Document" doesn't works

### ISSUE THREAD

**Issue by LuisDLR** [ljay79/jira-tools#36]
If I go to 'Manage' menu. 'Delete' button is missing.
If I select 'Do not use in this document' doesn't disappear in any case.

**Comment by ljay79** [comment]
Hi @LuisDLR sry but i do not really have an idea of what you are talking about.
Could you clarify to me and maybe even add some screenshots for better refence...

**Comment by LuisDLR** [comment]
Sorry, of course. 

**This is the 'Manage menu'**
![image](https://user-images.githubusercontent.com/32832486/31619073-01afb3f2-b294-11e7-814c-da5159537572.png)

**Here should be an 'remove' option**
**And if the first option 'Use in this document' is not selected, the plugin should not be active on the sheet that is in use**
![image](https://user-images.githubusercontent.com/32832486/31619273-4fdd1ab0-b294-11e7-8562-dd6e7cc64d5b.png)

Maybe this menu elements not are being managed for the developer.

**Comment by ljay79** [comment]
Ah ok. Thx for the info.
To be honest, i have never recognized this and never looked into it.

When i do same i can tell, i have in my test accounts at least the "Remove" option available.
The feature with "Use in this document" i will have to investigate.

May i ask, what the intention / reason for this would be - some practical use cases!?

**Comment by LuisDLR** [comment]
My main intention is to organize the plugins I use on each sheet. I don't always use all of them and the menu would be simpler to use.
The remove option is a matter of freedom :). Now your plugin is very useful to me but if I find a better option ...

Thank you very much for your work and sorry for my english

**Comment by ljay79** [comment]
The "remove" function is clear and actually works here. Please ensure you are logged on with proper account, i can only assume its related to maybe document permissions, ie: you are not the owner.. Remove should be possible in all cases, not even aware there is a way someone could disable this feature.

**Comment by ljay79** [comment]
Hi @LuisDLR 
i doubled check and read the documentation as well try to find some hints in the www.
Apparently is there no way for an Add-On to interfer with the options in the Manage Add-On screen.
Neither can i reproduce the issue.

"Use in this Document" is simply and switch to turn it off, which would disable the Add-On's background processes and other interferences but would not remove the Add-On from the menu.
As my Add-On has no Triggers or other hooks this option has no effect.
**As far as i understand it.

The "Remove" however is very curious, this should always be available for the user.
Please try to reload / refresh your browser and try it again. I can not think of any way, the "Remove" option would be hided, or not available for you.

If you can not solve this by yourself, i would ask you kindly to post a Help request with Google.

In case you find any solution, please be so kind and share it here with us.

**Comment by LuisDLR** [comment]
I found it!

I work in a google domain and the applications are managed by sysadmins.

Thanks for u help @ljay79

**Comment by ljay79** [comment]
Oh so your sysadmin installed the app and that is why you cant remove it yourself? Interesting

**Comment by LuisDLR** [comment]
That's it. Installation is controlled by Admins when domain account is used

**Comment by ljay79** [comment]
Glad we coul figure it out. I close this issue then.
