### ISSUE TITLE
Support Drop-down Custom Fields

### ISSUE THREAD

**Issue by ebiss** [ljay79/jira-tools#39]
Loving the new support for custom fields! For the metrics our company needs to pull, we need to be able to include custom fields that are a drop-down (called 'option') in order to fully use this add-on. Creating a new issue so I can track when you're able to support this functionality. Thanks!!

**Comment by ljay79** [comment]
wow...  i just released feature for request of custom fields and now already a request to extend it  hehe
You guys keep my busy for sure.

I can take a look into this, "Option" might be one of the more harder ones but still possible. 
As soon i reviewed these types i will let you know if this request is doable for me or not.

**Comment by ljay79** [comment]
Hi @ebiss 
please check out the latest release. It supports not more custom field types.
Please let me know if it works for you.

**Comment by ebiss** [comment]
@ljay79 all of the fields we need are now supported! Thanks so much for fighting the good fight :)

**Comment by ebiss** [comment]
@ljay79 can we re-open this issue? Right after I made my comment that it was working, I noticed that all the columns are showing up as blank for the custom fields and edited my comment. Probably should have just posted it in a new comment, I don't think you saw the updated one.

**Comment by ebiss** [comment]
@ljay79 I went back in and refreshed my list today and drop-down custom fields seem to be populating correctly now. Thanks for all your work on this! Last question- there is one last field that we could really use in order for this add-on to work for all of our needs. Any plans to support Epic Link anytime soon?

**Comment by ljay79** [comment]
Hi @ebiss i will look into this topic the next days and see how complicated or easy it would be.

**Comment by ljay79** [comment]
@ebiss pls do me a favour. As it appears, this specific issue here seems solved for you.
So i like to close this. For the request of adding support for "Epic Link" jira field, i would kindly ask you to create a new issue separatly.
