### ISSUE TITLE
Error "No custom fields available"

### ISSUE THREAD

**Issue by ljay79** [ljay79/jira-tools#40]
extracting issue from other unrelated and closed one
https://github.com/ljay79/jira-tools/issues/31#issuecomment-336949736

I tried the new release (checked it in the "About"). The problem is that when I try to configure custom fields I get the message 'No custom fields available! (red box in pop up). Can you tell me what the problem is? Do I have to make a new connection between JIRA and Google sheet? Do I have to change (define) something within JIRA itself?

**Comment by ljay79** [comment]
@JOPE51
First of all, yes you did correct. The provided user key was exactly what i meant.

I checked in the logs within StackDriver, sadly no errors logged for your session.
I can however see a few successfull logs.
Is it correct, the other function do work for you?

Are you actually sure, you do have custom fields in your used Jira instance?

Do you have a little technical background and might even be able to perform a curl or even Rest client request if i would give you instructions?

On a other note, i have (at least temporary) increate the api error logging specifically for the responsible part. Maybe in an hour or so, your Add-on will update autom. again.
Please give it a little time. Tomorrow please re test it again.

Open the "Configure custom fields", in case of an error, please report back here and provide again the then current user key (they change every session).
PS: Sry for any inconvenience.
![about-temp-user-key](https://user-images.githubusercontent.com/12184976/31634537-35d93af6-b2c4-11e7-9432-6c72ec9a80cb.jpg)

**Comment by JOPE51** [comment]
I can already tell you that the other function (using the standard fields) is working perfect.
As far as I know, we do use custom fields.  I will ask tomorrow to our 'JIRA administrator' if it is really so. Can you maybe tell me how I can see that we are working with custom fields?  I know that we defined new fields for our projects and outputs.

I'm not a programmer. I don't know if I have the technical background you need. For now, I don't know what you mean with 'be able to perform a curl or even Rest client request'? I'm certainly prepared to try.

**Comment by ljay79** [comment]
Jep sounds like you do have custom fields in Jira.
Last night i extended the logging a bit, can you please give it another try and report here. Please also copy again the "Temp User key" from the about dialog.

**Comment by JOPE51** [comment]
I did another try:
AFikiF3kacGA6pAvuI8V/4ANnTV2NhFiMxbgPuSSBYnX38SR+9GUuWEEXNAs4PUKDcf+PU3cKHnG

**Comment by ljay79** [comment]
Thx @JOPE51 
I believe i found the issue :)

Im damn scatterbrained.. forgot to add the new API method to the "Jira Server" api part.
Apparently you use Jira self hosted - server version and i do have an Cloud version to test again with.

Will push a BugFix in a few minutes.
Once updated you will see Build v0.19.1 in the About dialog and then i believe it should work for you.

**Comment by ljay79** [comment]
@JOPE51 
is your add-on already updated to version 0.19.1 ? (Check the "About" dialog).

Im confident the Custom Field feature should work then.

**Comment by JOPE51** [comment]
The add-on is indeed updated  to version 0.19.1.

**This is the current situation:**

In the popup 'Configuring custom fields, I can see the custom fields we defined.  I also see which type of custom field is supported (black or grey font). I selected some custom fields
![customfields2](https://user-images.githubusercontent.com/32700403/31677389-f3154fb4-b36a-11e7-97cc-4ca814fa2630.jpg)

When I go to List issues filter, under custom fields I see only one (I selected 6 or 7)
![customfields1](https://user-images.githubusercontent.com/32700403/31677358-d66885fc-b36a-11e7-9909-6a73f9ba20da.jpg)
When I run the add on, none of the selected custom fields is imported in the sheet


![customfields3](https://user-images.githubusercontent.com/32700403/31677399-f6bbf172-b36a-11e7-87fd-be14aa644b0d.jpg)

**Comment by ljay79** [comment]
Hi @JOPE51  thanks for the patience, and im a bit happy its at least moving forward :)
I can see any recent errors in StackDriver, but this doesnt mean much, as google wont log everything to me - obviously because of privacy :0

Anyway, do me a favor, try to select 1 or 2 fields only atm. Select one without any special characters in the name, i have a feeling the fields with ":" could make trouble.
So choose the "Outputtype" and maybe "Verantwoordelijk team" only, then tell me the results...

thx for helping me helping you  hehe

**Comment by JOPE51** [comment]
This is what I tried : (key : AFikiF3kacGA6pAvuI8V/4ANnTV2NhFiMxbgPuSSBYnX38SR+9GUuWEEXNAs4PUKDcf+PU3cKHnG)

Selection in "Configure custom fields". In your custom fields je see those which you suggested to select.
![customfields4](https://user-images.githubusercontent.com/32700403/31688061-6cf5a0d4-b38b-11e7-9851-9ad2f7f39913.jpg)

Settings on "List issues from filter"
As you can see only the 'outputtype' is shown under custom columns
![customfields5](https://user-images.githubusercontent.com/32700403/31688094-8dbc9228-b38b-11e7-9e73-3e934b9f2014.jpg)

On this picture you can see what the result is. Only the standard fields are imported. "R&A_NARA is the name of the filter > strange place (cell A2 under header Key)
![customfields6](https://user-images.githubusercontent.com/32700403/31688194-e1dfad36-b38b-11e7-8654-96e4be055299.jpg)

**Comment by ljay79** [comment]
hmmm wow... you really give me headache :)
I will see if i can find a bottleneck in my code which might cause this, but sadly i wont be able to test myself as this is highly depending on your custom Jira instance beside that i have only a Cloud instance available for testing.
I see, that i can review the code by tomorrow and provide you feedback...

Cell A2 (2nd line of new table) is always the place i write the used Jira Filter name into. That should be fine. Is it the actual name of your used filter or is it wrong as well? Its not visible on the selection screenshot...

.. and thanks for providing the user key - this is always helpful, even in this case i currently have no errors logged for your session.

**Comment by ljay79** [comment]
Hi @JOPE51 

as i assume you still have the issue and i couldnt find the problem yet, i spent some time improving the debugging options.
I have just released an update to v0.19.2 which has entirely remodelled debugging/logging.
In the "About" dialog you can now enable "Debugging" and provide me the temporary user key.
This will allow me to debug your issue much more better than i could before.

>As usual, Google StackDriver is taking user privacy very serious and it can be read how it works publicly available. On top, i made sure to remove any user credentials from the logging. My code is open source here on github and for everyone to review, improve, extend.

![about-debug](https://user-images.githubusercontent.com/12184976/31854795-80f7fb9c-b69f-11e7-869d-d23e69454057.jpg)

**Comment by JOPE51** [comment]
Hi,

The debugging is 'on' and the temporary key is : ALVeTPFWP8euFGPK7+JrfBVM3n3e3Iq8+HcEFkcDzauhvfWtEO9WniSZU+jR3U++c3heHaEdKI5G

I repeated the procedure as described earlier. The result is the same.

**Comment by ljay79** [comment]
Thanks @JOPE51  apparently the custom fields you use have no Jira key. Thats strange.
Can you please configure the fields again. Go to "Configure Custom fields" and remove all custom ones, press Save, then go back in and choose the ones you like to use and press Save again.

**Comment by JOPE51** [comment]
Done!

**Comment by ljay79** [comment]
Thank you. Have some useful logs i believe and will take a closer look at it tonight.

**Comment by ljay79** [comment]
@JOPE51 i found a bug, it was a incompatibility between Jira Server and Jira Cloud.
I believe, the issue is now fixed with my just released HotFix.

Please test it again and let me know if it now works. 
Thx

**Comment by JOPE51** [comment]
Key: 
ALVeTPFWP8euFGPK7+JrfBVM3n3e3Iq8+HcEFkcDzauhvfWtEO9WniSZU+jR3U++c3heHaEdKI5G
This is what changed:

- I can see now the selected custom columns in the popup 'List issues from filter'

- For the field 'Verantwoordelijk team' the content of the cell is something like _**{self=https://data.inbo.be/jira/rest/api/2/customFieldOption/10080, id=10080, value=Aquatisch beheer}**_ while it should be _**Aquatisch beheer**_. The type of this custom field is 'string', just like the other selected fields.

- Minor remark : There are 4 columns selected starting with the name 2018... A, 2018...B, 2018...C, 2018....D > in the export the order of the columns is different > A, C, B, D

- Question : Do you think that you can find a solution for the custom fields of the type 'array', 'user' and 'group'?

**Comment by ljay79** [comment]
Hi @JOPE51 

- the output of field _Verantwoordelijk team_ i will look into it.
- sorting of columns; i do actually not interfer with sorting/order of these and dont like to do. Simply because a alphabetic order might only suit some use case but not others. Its not possible to find one good sorting everyone will like, so i keep it straight and moving columns in the result table is as easy as drag&drop :)   sry
- about further custom field types; please add your comment up-vote to issue #39 

Thx for staying with me all the time, hope the add-on becomes now already more useful for you.
Would love to see you giving feedback in the add-on marketplace too.
https://chrome.google.com/webstore/detail/jira-sheet-tools/ncijnapilmmnebhbdanhkbbofofcniao?authuser=0

**Comment by ljay79** [comment]
@JOPE51 
the custom field "Verantwoordelijk team", you mention you get above code as a cell value in your sheet.
Can you please confirm that this kind of value is in all cells of the column for your custom field.
I researched a bit, i cant reproduce it myself, but these kind of value would actually only result on custom fields of type `option`.

I can only think of an explanation as following:
The custom field has been changed in your Jira project from field of type `option` to one of type `string` and now has mixed values.
If you can, maybe you can check this with your Jira administrator.

The only solution(s) at this point i can offer:
a) do not use this custom field
b) wait for me to release a newer update were i hopefully soon can support such custom fields of type `option`.

**Comment by tcorman** [comment]
We have this issue with one user, two others are fine. Problem user cannot see filters she created or our custom fields. Temp key for user with issue is ADKDv6BgqqiaqiAR6pF4mLoi9UVQQt434WH4lFWuy/jlaa6Z8wM5FJtfJfyEBUL42F1U2eAFx8Ri

Issue occurred today (Jan 24, 2019) between 10:15 AM and 10:30 Pacific time.

**Comment by ljay79** [comment]
Hi @tcorman i see u are back. With the same troubling user as in #89  ?
The log for above user key and timeframe show an Authorization Error:
```markdown
Unauthorized (401)
```

Please have credentials checked and permission of the user in Jira permissions.

**Comment by tcorman** [comment]
Hi @ljay79! The user in question has no problem seeing her filters in JIRA, or any other access issues. As far as I know she has the same JIRA permissions I have, and Sheet Tools works perfectly for me. Are there specific permissions in JIRA we should check?

**Comment by ljay79** [comment]
No that should be fine. How about the details entered in jira addons? Sure there is no typo in username or password?

Is your jira connected to Google domain for user account sync?

**Comment by tcorman** [comment]
I think our Jira Cloud is connected to GSuite, yes. She went to Atlassian and changed her password to be unique, but no change, still cannot see her filters or our custom fields. On Monday I'll sit with her and take a hard look at the authentication settings.

**Comment by ljay79** [comment]
The mentioned link i will investige deeper, if and how the difference is reflected in real world. Not sure how to detmine that behavior yet.
In best case, a user would (as suggested) create a API Token and use only his Atlassian username and API Token for the add-on.

https://id.atlassian.com/manage/api-tokens

If possible, you can actually try to perform the mentioned tests in CURL.
Basically as a base reference i would do this with a user (yours) which works, and then do the same with the problematic user.

You will need a valid Jira Issue Key from your system for the first test.
```markdown
curl -D- -u "username:password" -X GET -H "Content-Type: application/json" https://<your-jira-domain>.atlassian.net/rest/api/2/issue/<your-jira-issue-key> -k
```

```markdown
curl -D- -u "email:password" -X GET -H "Content-Type: application/json" https://<your-jira-domain>.atlassian.net/rest/api/2/issue/<your-jira-issue-key> -k
```

```markdown
curl -D- -u "username:password" -X GET -H "Content-Type: application/json" https://<your-jira-domain>.atlassian.net/rest/api/2/search?maxResults=1&jql=status%3DDone -k 
```

```markdown
curl -D- -u "email:password" -X GET -H "Content-Type: application/json" https://<your-jira-domain>.atlassian.net/rest/api/2/search?maxResults=1&jql=status%3DDone -k 
```
