### ISSUE TITLE
Property usable of null can not be read

### ISSUE THREAD

**Issue by snadales** [ljay79/jira-tools#46]
the plugin stopped importing data and / or update, I'm totally dead

![screenshot_3](https://user-images.githubusercontent.com/34747865/34264254-09e33d96-e651-11e7-8305-61c6357fb522.png)

**Comment by ljay79** [comment]
This bug should be fixed in latest add-on version 0.20.1.
Please check and let me know.

**Comment by richard-chudy** [comment]
able to update / import. perfect!
