### ISSUE TITLE
Hitting trigger limit when including Epic Custom Field

### ISSUE THREAD

**Issue by ebiss** [ljay79/jira-tools#47]
When I include the new Epic custom field in my filter, the add-on displays the first 3 lines (header, title, and 1 issue), then times out w/ the error:
"The add-on created too many "time-based" triggers for this Google user account in this document."
The add-on seems to handle returning the same filter just fine when I don't include the Epic field
I tried adding the Epic field to a different filter, and received the same error

**Comment by ljay79** [comment]
Hmm this is very strange.
For every Epic cell it will create a new trigger, but exactly because of the limitations, it is supposed to not add more than 2 trigger at any time.
I reviewed code and as of now, cant think of reason why it would create more.

Will see what i can do ...

**Comment by ljay79** [comment]
Closed due to inactivity.
In case there is still any problem, please open new issue.

**Comment by ljay79** [comment]
Identified the case, too many triggers get created and implemented a fix. Hope this issue is solved now.
