### ISSUE TITLE
Add more field options

### ISSUE THREAD

**Issue by jessieettinger** [ljay79/jira-tools#50]
Hi, I saw this was brought up in the last few months but I was unsure if anything has changed since then. This add-on is exactly what I'm looking for to update our execs on our current projects without them having to dig in Jira. However if there were a way to display both the linked issues and either label or custom label field, that would be even more helpful! 

Thanks

**Comment by ljay79** [comment]
Thx for your suggestion.
Can you please explain more detailed what you request with the "Label" and "Custom Label" part.

The JIRA system field "Labels" is already part of this Add-on and supported.
Custom fields are supported mainly, depending on the type of the field. Please check in the Add-On settings under "Configure Custom Fields" if your field is maybe already supported.

Adding all the "Linked Issues" would technically be possible for sure. I just think it will be to much overhead. With so many data requested from the API and extending it even more on the sheet like with "Epic" where additional subsequent API calls are required this Add-On is already troubling with performance and execution time limit of Google which can not be circumvented.

**Comment by jessieettinger** [comment]
I apologize for not being very explanatory. On the board I want to pull data from in Jira, I created a custom field called "Team(s) Involved" that using a label format (rather than drop down menu or checkbox for example) that ideally I would like to display. I was going to use the standard Jira label field to test the add-on out since I couldn't find my custom field but I am not seeing that option to use that one either. 

As for the linked issues, understood. I can manually display that data since I only want to show one of the relationships from the list.

**Comment by ljay79** [comment]
The Jira default field "Labels" is available per default in my Add-on when you go to "List Jira issues from Filter".
![field-labels](https://user-images.githubusercontent.com/12184976/34787117-7e730b38-f636-11e7-931f-09eb34732c53.jpg)

Your custom field "Teams involved" of type "label" is currently not support.
I will find some time and see if i can implement support for it.
Can you confirm, your custom field is of type "Labels" as shown in Jira Field Configuration Screenshot here?
![customfield-label](https://user-images.githubusercontent.com/12184976/34787321-2427b858-f637-11e7-90e0-4cb6d2818133.jpg)

**Comment by jessieettinger** [comment]
Thanks for pointing out the Jira labels! Totally missed it. 

And yes, my custom field is a label. Thank you, I appreciate it! 

![custom_fields_-_jira](https://user-images.githubusercontent.com/32879113/34791801-ae42be06-f60b-11e7-8f9c-acd4b808ece4.jpg)

**Comment by ljay79** [comment]
Hi @jessieettinger 
Check out the latest version (add-on will automatically update to v0.20.2).
It will now support the Jira "Labels". You can configure it in settings of the Add-on "Configure Custom Fields".
