### ISSUE TITLE
Cannot log in with Google Account

### ISSUE THREAD

**Issue by shibucyriac** [ljay79/jira-tools#51]
I usually log into Atlassian using my corporate google account. How can I use the same with Google Sheet Tools

**Comment by ljay79** [comment]
Hi @shibucyriac  and welcome.
This is a known issue when using Jira with G-Suite synced.
Please read the Readme here in section _[Known Issues](https://github.com/ljay79/jira-tools#known-issues)_.

Let me know if this didnt helped.

**Comment by ljay79** [comment]
closed due to inactivity
