### ISSUE TITLE
Feature request: Time report for a given project

### ISSUE THREAD

**Issue by steve-purkis-inviqa** [ljay79/jira-tools#54]
Hi @ljay79,

Thanks for your work on this open-source plugin!

I was hoping to use it to simplify time reporting for projects; to do that I'd need to be able to download time logs per project rather than per user.  From a UI perspective, the only thing that would need to change is introducing a project selector where you currently have a user selector.  Under the hood, it would hit the Jira API to fetch all timelogs to that project for the given period.

Hope this idea helps,
-Steve

**Comment by ljay79** [comment]
Hi @steve-purkis-inviqa  thanks for your feedback.

Unfortunately i doubt i can implement something like this.
I do have my own little expirience with time reports via API with Jira, and i can tell you, it is simply to extensive data and api requests, that it would work efficiently within the limitations of google sheet app scripts.

For such heavy time reports, i can recommend to take a look at Jira Plugins - directly within Jira.
Im using "Timesheet Reports". Which is very simple but delivers most data i need.
Try it from the Jira Marketplace:
[Timesheet Reports](https://marketplace.atlassian.com/plugins/jira-timesheet-plugin/cloud/overview)

**Comment by steve-purkis-inviqa** [comment]
Hi @ljay79, we currently use [Tempo](https://marketplace.atlassian.com/plugins/is.origo.jira.tempo-plugin/cloud/overview), which is ok for exporting via CSV, but I'd prefer to automate it :).  I appreciate it's not something you'll be able to take on.

**Comment by ljay79** [comment]
Yeah sry. Just based on my experience with it during the development of this add-on, I wouldn't know how to handle such amount of data and api request needed for it within the limitations of google app script.

Thx for understanding. Hope this add-on can still be benificary for you.
