### ISSUE TITLE
Feature request: download & aggregate workflow state transitions

### ISSUE THREAD

**Issue by steve-purkis-inviqa** [ljay79/jira-tools#55]
Hi @ljay79,

Thanks again for this plugin.  I was hoping to use it to produce better Lean/Kanban analytics than Jira currently provides. To do that I'd need to be able to download and aggregate workflow state transitions.

From a UI perspective, I see this as an extension to the List Issues from Filter" feature you currently have.

As an example, given a workflow:

>  `Todo --> In Progress --> In Review --> Done`

I'd like to download a list of tickets with any fields I've selected, and also:
1. download and aggregate time spent in each workflow state.
1. note first time ticket entered into each workflow state (so I can calculate cycle time across different states, and overall lead time)

Hope this idea helps,
-Steve

**Comment by ljay79** [comment]
Hi.

Looks like this feature request would depend on #54 and therefor get same declinal sadly.
If not, i might not really understood the request and hope you can elaborate it more.

**Comment by ljay79** [comment]
I will have a look into it soon and come back on that.

**Comment by ljay79** [comment]
After reviewing this request i believe this is most likely already possible inside JIRA on the filter result page where it allows to download all results in different output format.

While this would be a very specific feature for a very specific and custom use case as i understand it atm, i do not see it as a good fit for this little add-on which focuses on a few most common use cases.

Sry, but i hope you can still make use of this add-on for your other use cases.
