### ISSUE TITLE
Problem with automatic schedule and refresh data now function

### ISSUE THREAD

**Issue by JiraFun** [ljay79/jira-tools#57]
2 questions.

1) When I configure the connection under Jira Add-Ons it looks fine.
  i) connection is established
 ii) I can see and configure custom fields
 iii) I can select a filter and it will populate on the selected page as expected

When I 

Question 1. 
Using the wizard - it asks to define a issue type (store, epic or bug) - what would the syntax be if I have issue types with spaces and brackets eg: I have several issue types simliar to this.. 
Standard RICEF (Design Only)
Standard RICEF (Design and Dev)

and Im not sure if this is causing an issue with the script...

Question 2.
Whenever I refresh the data - I receive an error - however listing from a filer works? which seems bit odd.

**Comment by ljay79** [comment]
Hi @JiraFun 

1)
As far as i know, the special characters in the Epic/Issue name should not cause any isses with the Sheet Add-on.

2)
Can you post the error message.
Could you also maybe activate Debugging in the "About" dialog and post me your temp user key, this way i can trace a little in the stack driver logs.

**Comment by ljay79** [comment]
closed due to lack of information and activity.
