### ISSUE TITLE
Custom Fields - add Status and Resolution (Workflow Elements)

### ISSUE THREAD

**Issue by Whynot23** [ljay79/jira-tools#60]
Feature Request Pretty Please

**Comment by ljay79** [comment]
Hi @Whynot23 
please check, the requested 2 Jira fields are part of the default supported fields and can be found in the dialog when listing issues from filter.

![status-resolution](https://user-images.githubusercontent.com/12184976/36355061-825c9fbe-14dd-11e8-8302-2cbd853803fa.jpg)
