### ISSUE TITLE
What does Refresh Ticket Data really do?

### ISSUE THREAD

**Issue by jennychiu** [ljay79/jira-tools#63]
HI, 
What does Refresh Ticket Data really do? 
I pulled a list of jira tickets with custom fields into a sheet, and then updated some of the information in the custom fields within Jira. Then, I wanted to refresh the sheet with the updated info so I clicked on the Refresh Ticket Data button but nothing on the sheet was updated. Is this a bug? Am I doing it wrong?

**Comment by ljay79** [comment]
Hi.
Try following to discover.
Open a new sheet, enter any if your valid issue id e.g. "JST-123".
Then use the action "Refresh Ticket Data".

For more details check the Readme here in GitHub. https://github.com/ljay79/jira-tools/blob/develop/README.md
