### ISSUE TITLE
jira-tools not available in google Add-on's

### ISSUE THREAD

**Issue by simonjaz** [ljay79/jira-tools#64]
Not available on google Add-on's. Was removed with purpose?

**Comment by jennychiu** [comment]
I was wondering the same thing. It was still up last week and now it's not there.

**Comment by ljay79** [comment]
Hi.
No that is unintended for sure.
Will write Google to check for status and reason.

I could imagine, that due to me updating the Authors name last night, that this unknowingly initiates like a full reset and review of the add-on entirely.

Will let you know, as soon i have news.

**Comment by ljay79** [comment]
I emailed google and got already feedback.
Add-on is now back available, it only got stuck in their review queue they told me.

Thx for bringing it to my attention that fast.
