### ISSUE TITLE
customize to search only in one column not whole sheet

### ISSUE THREAD

**Issue by chaycesol** [ljay79/jira-tools#65]
Hi! I'm new to API's and I love what you did here with this. Question is I was trying to edit the script off of what you based this off of https://gist.github.com/rtrcolin/4455097 and wanted to know how you can edit the script so that way it will only look for the "KEY-123" value in one column only (i.e. only specify to search Column A) vs looking at the whole sheet?

**Comment by ljay79** [comment]
Hi @chaycesol i guess this request then i better to put at the Repo from @rtrcolin .
I guess you would start editing the function _function refreshTickets(){_ so it would select only a specific range in your sheet to search for issue keys.
Like _sheet.getRange("A1:A")_
https://developers.google.com/apps-script/reference/spreadsheet/range

**Comment by ljay79** [comment]
closed - wrong repo for this request
