### ISSUE TITLE
Active sprint

### ISSUE THREAD

**Issue by alexgarner** [ljay79/jira-tools#68]
When I run a report using the filters - which is exactly what I wanted to use - it does not seem to pull in active sprint data. And from a few spot checks, other closed tickets are not appearing. Can you shed any light - are we doing something wrong?

**Comment by ljay79** [comment]
What this import does, it uses a predefined filter and fetches all resulting jira issues. Regardless of any relation to a sprint.

It should return you a full list of all tickets in the sheet, which you would also get, when you view the exact same filter in Jira itself.

**Comment by ljay79** [comment]
Could you figure what was the reason for not matching your expectation? Did you solve this?

**Comment by ljay79** [comment]
closed due to inactivity
