### ISSUE TITLE
Login with Google

### ISSUE THREAD

**Issue by buhpasca** [ljay79/jira-tools#72]
We use the "login with google" button on the jira website. So I have no password and it's therefore not possible to use your tool (?)

**Comment by ljay79** [comment]
Hi @buhpasca

Yes it is possible to use this add on even in your case.
We/me doing the exact same.

Please see the readme where the solution is described.
https://github.com/ljay79/jira-tools/blob/develop/README.md#known-issues

**Comment by buhpasca** [comment]
Hi Jens

Wow thanks for your very fast reply! Will test it out tomorrow. :-)

------ Originalnachricht ------
Von: "Jens" <notifications@github.com<mailto:notifications@github.com>>
An: "ljay79/jira-tools" <jira-tools@noreply.github.com<mailto:jira-tools@noreply.github.com>>
Cc: "Buholzer Pascal" <pascal.buholzer@mavt.ethz.ch<mailto:pascal.buholzer@mavt.ethz.ch>>; "Mention" <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Gesendet: 18.04.2018 19:55:23
Betreff: Re: [ljay79/jira-tools] Login with Google (#72)


Hi @buhpasca<https://github.com/buhpasca>

Yes it is possible to use this add on even in your case.
We/me doing the exact same.

Please see the readme where the solution is described.
https://github.com/ljay79/jira-tools/blob/develop/README.md#known-issues

**Comment by buhpasca** [comment]
Nice Jens it worked like a charm :-)

------ Originalnachricht ------
Von: "Jens" <notifications@github.com<mailto:notifications@github.com>>
An: "ljay79/jira-tools" <jira-tools@noreply.github.com<mailto:jira-tools@noreply.github.com>>
Cc: "Buholzer Pascal" <pascal.buholzer@mavt.ethz.ch<mailto:pascal.buholzer@mavt.ethz.ch>>; "Mention" <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Gesendet: 18.04.2018 19:55:23
Betreff: Re: [ljay79/jira-tools] Login with Google (#72)


Hi @buhpasca<https://github.com/buhpasca>

Yes it is possible to use this add on even in your case.
We/me doing the exact same.

Please see the readme where the solution is described.
https://github.com/ljay79/jira-tools/blob/develop/README.md#known-issues

**Comment by ljay79** [comment]
Im glad it works. I close this issue now.
Feel free to open an new issue in case you have any problems.

I do appriciate, if you submit a review in the google add-on marketplace - maybe after you tested it a little bit more.
