### ISSUE TITLE
No data showing in sheet

### ISSUE THREAD

**Issue by mattdotroberts** [ljay79/jira-tools#73]
Unclear what I am doing wrong? Connected OK but no rows/columns updated. Just an empty sheet

**Comment by ljay79** [comment]
Did you try to insert issues from filter? Anything? Any error or other feedback?

**Comment by ljay79** [comment]
Thx @mattdotroberts im glad you figured it out.
I will check why this happens and in if thats normal operation in the api, then certainly update the guide / help.

**Comment by ljay79** [comment]
Explanation for using filters improved in release [v0.23.0](https://github.com/ljay79/jira-tools/tree/v0.23.0)
