### ISSUE TITLE
Missing data from custom field

### ISSUE THREAD

**Issue by pmcarter3rd** [ljay79/jira-tools#74]
I created a custom field called "Sprint",  ran a filter and selected Sprint.  The sprint name is returned randomly.  Some issues contain the correct sprint name and others don't.  I've noticed in Jira when listing a "Sprint" it sometimes contains more than one value - don't know if this is causing the issue?

![jira-1](https://user-images.githubusercontent.com/38145143/39269231-2cec913c-4887-11e8-84ad-06b95085500a.JPG)
![jira-2](https://user-images.githubusercontent.com/38145143/39269232-2d059aec-4887-11e8-8534-be660c315167.JPG)

**Comment by ljay79** [comment]
Hi @pmcarter3rd thx for taking the time to report the issue, i will have a look at it as soon i get a chance.
If you could pls activate debugging, provide the shown temp user key and run a report with such issue again, this would provide me with some insights in the underlying requests and data fetched.

Btw: What field type is your custom field "Sprint", as you configured it in Jira custom fields?

**Comment by Rygression** [comment]
This is really great. Having trouble getting two custom fields to show up for a query with only ~10 results. Any idea if that's related to the above?

**Comment by ljay79** [comment]
Hi @Rygression what query are ou using. Could you pls open a new issue and describe your problem in detail.

**Comment by ljay79** [comment]
@pmcarter3rd any update on that issue to my question(s) https://github.com/ljay79/jira-tools/issues/74#issuecomment-385458474

**Comment by ljay79** [comment]
Closed due to inactivity / not reproducable
