### ISSUE TITLE
Support Google Auth

### ISSUE THREAD

**Issue by csherrard** [ljay79/jira-tools#75]
My organization uses Google Auth for single sign-on to Jira.  It would be nice if Jira Sheet Tools allowed for g-auth sso.

**Comment by ljay79** [comment]
Hi , pls check out the readme in section 'Known Issues'
https://github.com/ljay79/jira-tools#known-issues

Let me know, if it solves your issue.

**Comment by csherrard** [comment]
Thank you so much @ljay79 !!  my team is going to **LOVE** this addon.
