### ISSUE TITLE
Missing Field: Resolved

### ISSUE THREAD

**Issue by rvallenduuk** [ljay79/jira-tools#76]
Resolved (Date field) is shown in your Jira field map but is not available to select in List Issues from Filter.
It's a system field, not a custom field.

**Comment by ljay79** [comment]
Thx @rvallenduuk for pointing that out. Will have a look and see if/how to support it as a default system field.

**Comment by ljay79** [comment]
Hi @rvallenduuk , i have identified the system field and could add support for it as part of the "System columns" for the "List issue from Filter" feature.
Will update you here again in a few days, when i have rolled out an add-on update.

**Comment by ljay79** [comment]
Support for "Resolved" field added in [Release v0.23.0](https://github.com/ljay79/jira-tools/tree/v0.23.0)
