### ISSUE TITLE
API Tokens for Jira access

### ISSUE THREAD

**Issue by hudeldudel** [ljay79/jira-tools#77]
Instead of setting a password for G-Suite synced accounts, you may recommend to generate an API Token instead. This is better security and also works for Jira accounts with two-step verification enabled.
https://confluence.atlassian.com/cloud/api-tokens-938839638.html

I tried jira-tools with an Jira Cloud API Token and it worked fine. Simply paste the API Token into the password field in the Jira Sheet Tools Settings.

**Comment by ljay79** [comment]
Thx @hudeldudel , will try this asap and then probably offer as a solution.

**Comment by ljay79** [comment]
README updated to recommend use of API Tokens.

[Release v0.23.0](https://github.com/ljay79/jira-tools/tree/v0.23.0)
