### ISSUE TITLE
Story points with "0" are not returned in search 

### ISSUE THREAD

**Issue by player2** [ljay79/jira-tools#84]
When 0 has been entered against Story points the name of the customer field is returned in the search.

Steps 
1. Create a JIRA issue with a value of 0 story points 
2. Create a JST_search that return this issues and displays the story points in the results 
*Observe:* Instead of displaying 0 points the name of the customfield is displayed i.e. "customfield_10105"

**Comment by ljay79** [comment]
Hi @player2 , im afraid to let you know, that the custom function _JST_search_ does not yet support custom fields.
