### ISSUE TITLE
Limited Users

### ISSUE THREAD

**Issue by mwahaj08** [ljay79/jira-tools#85]
Whenever I want to generate time reports I am able to see a limited list of Users. It only shows 50 users from my Jira.

**Comment by mwahaj08** [comment]
I understand your point @ljay79  we are currently deleting all the inactive users, hopefully, we will get rid all of them but for now its only showing 50 instead of 100. I will let you know if it still shows fewer users after removing inactive users. Thanks.

**Comment by ljay79** [comment]
Found a silly bug which did ignore my default result set of max 100 users in total. Have it fixed and same time increased limit to max 250 users and 250 groups.
Will be part of next release (within next days i believe).

**Comment by ljay79** [comment]
New version 1.2.2 is now approved by Google and published.
You can try the new user selection with autocomplete when create a time report.
New limitation of **1000 users** (limited by Jira API).

Let me know, if there are any issues.
So far, i will close this issue - commenting should still be allowed.

When you like the Add-On, i do appriciate a positive review in the Google Marketplace:
https://chrome.google.com/webstore/detail/project-aid-for-jira/ncijnapilmmnebhbdanhkbbofofcniao
