### ISSUE TITLE
No refresh for filter?

### ISSUE THREAD

**Issue by tcorman** [ljay79/jira-tools#90]
This is a really  beautiful thing, thank you for it. I might be missing something, but it looks to me like, if you populate a Google Sheet doc from a JIRA filter, it does not refresh if you reload the page, or close and reopen it. Is there a Refresh function, or do I need to delete and re-add the filter output to update the Google doc?

**Comment by ljay79** [comment]
Hi @tcorman

For data inserted into the sheet via the dialogs this is the intended and expected behavior. That plain data can not be refreshed and can only be overwritten by repeating the flow.
