### ISSUE TITLE
Sprint Data Not Exporting Consistently

### ISSUE THREAD

**Issue by jckutz** [ljay79/jira-tools#93]
When using the "List Issue From Filter" functionality, and the Custom Column Sprint field from Jira, I am noticing that some issues do not have Sprint in my export, even though in Jira they do have a Sprint value (current sprint or future sprint).  I adjusted my filter to order by sprint, and I'm now seeing that exactly every other record contains a sprint value, the rest do not. 

I'm using JIRA cloud version and Jira Sheet Tools v1.0.0

**Comment by ljay79** [comment]
Hi @jckutz 

if you dont mind, pelase activate Debugging in "About" dialog, provide me your "Temp. User Key" and then perform at least one another try. This way it will log the error and information to my StackDriver logging account where i can analyze it better.
User credentials are not transmitted in any log data.

**Comment by jckutz** [comment]
Hi @ljay79 . Thanks for the quick response. I ran it a few times with debug on, here is my Temp User Key: AH64fx0p5ZMMqZ/F3TaacEs+ZowM9xAcni30Ibx4QCVuHlUoSTfArw6P3KEj0Nxav+sbJI0OQb7M

Thanks for looking into this, great tool by the way, simple but helpful!

**Comment by PowerMarcello** [comment]
Hi,
we have the same problem, please help us.
Key: AH64fx1HH7gRj/4c4UoUEXm9f+1I9XaNHBRy4SE1S4sauTv7zqxLl/EqSnsxnTwmklJSK7hFMMuQ

**Comment by ljay79** [comment]
Version 1.0.1 is now available via the GAS & Auto-Update which should fix the issue with Sprint value only showing up on every other record.

**Comment by ljay79** [comment]
@jckutz , @blakenan , @PowerMarcello can you guys confirm that the bug with the Sprint data is now fixed since version 1.0.1 .

**Comment by jckutz** [comment]
Hi @ljay79 , after several tests, it looks like the issues has been resolved. I'm also getting multiple sprint values if Jira has them stored that way.

Thank you for a quick turnaround!

**Comment by ljay79** [comment]
Im glad it works now.
