### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by crlazar** [ljay79/jira-tools#94]
Hello,

While trying to retrieve the JIRA tickets I'm unable to retrieve Custom Fields from specific filters while in others that is possible.
The custom fields are support and in a date / time format.

Any idea why?

Thank you.

**Comment by ljay79** [comment]
Hi @crlazar 
how do you try to retrieve the data? Is it maybe related to #84

**Comment by crlazar** [comment]
Yes via dialog, List issue from filter.

**Comment by ljay79** [comment]
@crlazar i have tried to verify and reproduce your explained issue.
I do have 2 custom fields, one is of type "Date Picker" and the other "Date Time Picker".
Both are displayed correctly.

You mentioned, it works in some saved filter but not in all.
Can you please provide some more details on how i could try to replicate your specific circumstances.

ie:
- what is the difference in a filter that works vs. one that doesnt work
- what exact custom field types are you using
- what jira version
- how many results are expected in your filter
- how many fields are you selecting in the dialog to output in the sheet
- provide the JQL query used for a *not* working filter

Please also give it a test, use a filter which doesnt work currently and limit the number of results by applying (temporary) more attributes so you are sure it results in less than 100 issues.

Last but not least, if you dont mind, pelase activate Debugging in "About" dialog, provide me your "Temp. User Key" and then perform at least one another try. This way it will log possible errors and information to my StackDriver logging account where i can analyze it better.
User credentials are not transmitted in any log data.

**Comment by ljay79** [comment]
Hello @crlazar as the add-on now since a few months does support any custom field of type "date" or "datetime", do you still expirience the above mentioned behavior?
