### ISSUE TITLE
Custom Field which has checkboxes is not importing

### ISSUE THREAD

**Issue by rake23** [ljay79/jira-tools#98]
I have a custom field which has various checkbox options. This field is getting blank while importing. It should import all the selected options

Ex: Fix Category

- [ ] Issue Type 1

- [ ] Issue Type 2  

- [ ] Issue Type 3

**Comment by ljay79** [comment]
Hi @rake23 
i see, i can confirm this behavior. Will check what the cause is.

**Comment by ljay79** [comment]
@rake23 could you please confirm that latest add-on update did fix the issue. Thx

**Comment by rake23** [comment]
@ljay79 
It is working great. Thanks for fixing so fast.
